"""Record frozen motion evaluation and serial responsiveness diagnosis."""
import copy,time
from checkpoint_expanded_goal_v19 import ROOT,read,write,sha,g
from evaluate_milestone_goal_v2 import evaluate

def main():
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/';cp=read(base+'checkpoint-tangent-training-v1.json');old=read(cp['state_path']);s=copy.deepcopy(old);previous=cp['evidence'];e=read(previous);assert cp['round']==63 and s['contract']['max_goalposts']==100 and cp['deadline_unix']==1789053845.
 changed={n for n,h in e['artifacts'].items() if sha(n)!=h};assert not changed,changed
 dev=read(res+'sequence-tangent-development-v1/report.json');comparison=read(res+'sequence-tangent-development-v1/comparison-to-previous.json');profile=read(res+'private-phase-profile-v1/report.json');assert dev['complete'] and dev['protected_baselines_match'] and dev['validation_windows']==768 and not dev['confirmation_read'] and not dev['runtime_promoted'];assert comparison['complete'] and not comparison['acceptance_changed'];assert profile['complete'] and len(profile['runs'])==2 and all(r['source_preserved'] and r['inventory_preserved'] and r['exact_between_runs'] for r in profile['runs'])
 assert profile['runtime_sha256']==read(res+'private-production-benchmark-v1/report.json')['runtime_sha256'];assert read(base+'tangent-development-progress-v1.json')['status']=='complete'
 inputs=[tr+n for n in ('finalize_tangent_development_v1.py','checkpoint_tangent_development_v1.py')]+[base+'TANGENT-SEQUENCE-DEVELOPMENT-v1.md',base+'PRIVATE-PHASE-PROFILE-v1.md'];added=[n for n in inputs if n not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract']);a=copy.deepcopy(s['contract']);b=copy.deepcopy(old['contract']);a.pop('inputs');b.pop('inputs');assert a==b
 s['explicit_revisions'].append(dict(reason='Both fixed tangent models evaluated against unchanged controls and original gates; serial private-preview profiling completed. Same endpoint, limits, floors and deferrals; no source change or model promotion.',prior_state=cp['state_path'],prior_sha256=sha(cp['state_path']),added_inputs=added,prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],recorded_at=time.time()))
 paths=set(e['artifacts'])|set(inputs)|{cp['state_path'],previous,base+'checkpoint-tangent-training-v1.json',base+'tangent-development-progress-v1.json'}
 for folder in ('sequence-tangent-development-v1','private-phase-profile-v1'):paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/folder).rglob('*') if p.is_file())
 assert all(not (ROOT/tr/'cache'/(n+'.bvh')).exists() for n in read(tr+'temporal_expansion_plan_v19.json')['planned_splits']['confirmation'])
 fp=g.fingerprint(ROOT,s['contract']['inputs']);e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={n:sha(n) for n in sorted(paths)},previous_evidence_recheck=dict(path=previous,sha256=sha(previous),all_artifacts_unchanged=True),tangent_development=dict(report=res+'sequence-tangent-development-v1/report.json',family_passes=dev['family_passes'],baselines_exact=True,windows=768,runtime_promoted=False,confirmation_read=False),private_phase_profile=dict(report=res+'private-phase-profile-v1/report.json',unprofiled_max_tick=profile['runs'][0]['max_tick_seconds'],native_exit_code=read(res+'private-phase-profile-v1/process.json')['exit_code'],ui_qualified=False,source_changed=False))
 e['qualification'].update(temporal_model_qualification=False,independent_usability='unknown',full_goal_complete=False);ep=gp+'tangent-development-evidence-v1.json';write(ep,e);obs=read(gp+'tangent-training-observations-v1.json')
 for group in obs.values():
  for row in group.values():row.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 op=gp+'tangent-development-observations-v1.json';write(op,obs);end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];g.record_work(s,'controller-tangent-development-v1',duration);result=evaluate(s,obs,ROOT)
 assert result['round']==64 and result['decision']=='iterate' and s['history'][:-1]==old['history'] and s['floors']==old['floors'];result['evidence_transport_note']='Signed assessment and independent review unavailable; original endpoint remains incomplete. Development decisions and profiling evidence are recorded without claiming human usability or Cascadeur parity.';s['history'][-1]=result;dest=gp+'01a073fe-c240-70c0-b5cd-fe9653aac60e-tangent-development-v1.json';assert not (ROOT/dest).exists();write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result)+'\n\n'+result['evidence_transport_note']+'\n',encoding='utf-8')
 cp.update(state_path=dest,last_evaluated_state=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=64,remaining_evaluations=36,evidence=ep,decision='iterate',stagnant_rounds=s['stagnant_rounds'],next_controller_monotonic_start=end,active_jobs=[],recorded_at=time.time(),current_turn_classification='Progress: complete fixed development evaluation and serial preview-phase profiling; original controls and protected evidence preserved.',previous_turn_classification='Progress: two controlled fits and export/inference contracts completed.',blocked_audit=dict(consecutive_goal_turns=0,condition=None),work_accounting='Parent active-work interval recorded once; no child runtime added.',pending_source_revisions={},pending_document_revisions={})
 cp['latest_live_observation']=dict(development=read(res+'sequence-tangent-development-v1/controller-receipt.json'),profile=read(res+'private-phase-profile-v1/controller-receipt.json'));cp['next_safe_actions']=['All tracked jobs terminal. Read TANGENT-SEQUENCE-DEVELOPMENT-v1.md and PRIVATE-PHASE-PROFILE-v1.md before deciding the next change.','Do not launch another nearby fit automatically. Preserve both fixed outcomes and original gates; further learning work needs a new bounded data/workflow/model hypothesis.','Profile points to visible-state guard traversal and final publication/smoothing. Investigate allocation/traversal reduction while preserving every guard boundary; incremental publication requires isolated candidates and cancellation/lifecycle recovery. No validation weakening.','Keep six confirmation clips sealed, full endpoint,100evaluation cap,deadline1789053845,original floors and prior deferrals.','No temporal model or Cascadeur parity is qualified. Continue full intent/contact/physics, rig, native workflow and independent human requirements.'];write(base+'checkpoint-tangent-development-v1.json',cp);print(dict(round=64,remaining_evaluations=36,prior_artifacts=len(read(previous)['artifacts']),artifact_count=len(paths),work_seconds=duration,development=dev['family_passes'],all_jobs_terminal=True,full_goal_complete=False))
if __name__=='__main__':main()
