"""Record completed controlled fits, preserving the full original endpoint."""
import copy,time
from checkpoint_expanded_goal_v19 import ROOT,read,write,sha,g
from evaluate_milestone_goal_v2 import evaluate

def main():
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/';cp=read(base+'checkpoint-sequence-context-v1.json');old=read(cp['state_path']);s=copy.deepcopy(old);previous=cp['evidence'];e=read(previous)
 assert cp['round']==62 and s['contract']['max_goalposts']==100 and cp['deadline_unix']==1789053845.
 changed={n for n,h in e['artifacts'].items() if sha(n)!=h};assert not changed,changed
 folder=res+'sequence-tangent-training-v1/';assert read(folder+'active-process.json')['all_complete'];processes=read(folder+'processes.json');assert len(processes)==2 and all(p['exit_code']==0 for p in processes)
 fits=[]
 for seed in (20260909,20260910):
  check=read(res+'sequence-tangent-provider-'+str(seed)+'/report.json');assert check['passed'] and check['tests']==6
 for seed in (20260909,20260910):
  p=folder+'direct-'+str(seed)+'/report.json';r=read(p);assert r['complete'] and r['completed_epochs']==60 and r['cpu_export_max_abs_error']<5e-5 and not r['validation_read'] and not r['confirmation_read'];assert r['augmentation']['original_arrays_unchanged'] and r['augmentation']['windows']==5778;assert sha(r['weights'])==r['weights_sha256'];fits.append(dict(seed=seed,report=p,report_sha256=sha(p),weights=r['weights'],weights_sha256=r['weights_sha256'],final_training_loss=r['history'][-1]['mean_training_loss']))
 portability=read(res+'sequence-tangent-portability-v2/host.json');assert portability['complete'] and len(portability['cases'])==3 and all(r['torch_numpy_max_abs_error']<5e-5 for r in portability['cases']);assert read(res+'sequence-tangent-source-audit-v1.json')['passed'];visual=read(res+'frozen-sequence-visuals-v1/report.json');assert visual['complete'] and not visual['active_training_weights_read']
 inputs=[tr+n for n in ('sequence_tangent_model_v1.py','sequence_tangent_numpy_v1.py','sequence_tangent_provider_v1.py','sequence_tangent_training_data_v1.py','check_sequence_tangent_portability_v1.py','check_sequence_tangent_portability_v2.py','train_sequence_tangent_v1.py','sequence_tangent_fit_plan_v1.json','evaluate_sequence_tangent_v1.py','evaluate_sequence_tangent_v2.py','sequence_tangent_evaluation_plan_v1.json','sequence_tangent_evaluation_plan_v2.json','render_frozen_sequence_visuals_v1.py','checkpoint_tangent_training_v1.py','check_sequence_tangent_provider_v1.py','profile_private_phases_v1.py','finalize_tangent_training_v1.py')]+[base+'FROZEN-MOTION-COMPARISONS-v1.md',base+'TANGENT-SEQUENCE-TRAINING-v1.md']
 added=[n for n in inputs if n not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract']);a=copy.deepcopy(s['contract']);b=copy.deepcopy(old['contract']);a.pop('inputs');b.pop('inputs');assert a==b
 s['explicit_revisions'].append(dict(reason='Two fixed tangent-conditioned direct fits and nontrivial native export checks completed; frozen failure visuals prepared. Development remains pending; no promotion or endpoint change.',prior_state=cp['state_path'],prior_sha256=sha(cp['state_path']),added_inputs=added,prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],recorded_at=time.time()))
 paths=set(e['artifacts'])|set(inputs)|{cp['state_path'],previous,base+'checkpoint-sequence-context-v1.json',gp+'sequence-tangent-fit-routing-v1.json',gp+'frozen-sequence-visuals-routing-v1.json',res+'sequence-tangent-source-audit-v1.json',res+'sequence-tangent-plan-provenance-v1.json',gp+'private-phase-profile-routing-v1.json'}
 for name in ('sequence-tangent-portability-v1','sequence-tangent-portability-v2','sequence-tangent-training-v1','frozen-sequence-visuals-v1','sequence-tangent-provider-20260909','sequence-tangent-provider-20260910'):
  paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/name).rglob('*') if p.is_file())
 assert all(not (ROOT/tr/'cache'/(n+'.bvh')).exists() for n in read(tr+'temporal_expansion_plan_v19.json')['planned_splits']['confirmation'])
 fp=g.fingerprint(ROOT,s['contract']['inputs']);e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={n:sha(n) for n in sorted(paths)},previous_evidence_recheck=dict(path=previous,sha256=sha(previous),all_artifacts_unchanged=True),tangent_training=dict(fits=fits,native_portability=res+'sequence-tangent-portability-v2/host.json',native_process_exit=read(res+'sequence-tangent-portability-v2/processes.json')[-1]['exit_code'],development_evaluated=False,runtime_promoted=False,full_goal_complete=False))
 e['qualification'].update(temporal_model_qualification=False,independent_usability='unknown',full_goal_complete=False);ep=gp+'tangent-training-evidence-v1.json';write(ep,e);obs=read(gp+'sequence-context-observations-v1.json')
 for group in obs.values():
  for row in group.values():row.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 op=gp+'tangent-training-observations-v1.json';write(op,obs);end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];g.record_work(s,'controller-tangent-training-v1',duration);result=evaluate(s,obs,ROOT)
 assert result['round']==63 and result['decision']=='iterate' and s['history'][:-1]==old['history'] and s['floors']==old['floors'];result['evidence_transport_note']='Signed assessment and independent review unavailable; completed fixed fits do not establish development quality, animator usability or Cascadeur parity.';s['history'][-1]=result;dest=gp+'01a073fe-c240-70c0-b5cd-fe9653aac60e-tangent-training-v1.json';assert not (ROOT/dest).exists();write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result)+'\n\n'+result['evidence_transport_note']+'\n',encoding='utf-8')
 cp.update(state_path=dest,last_evaluated_state=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=63,remaining_evaluations=37,evidence=ep,decision='iterate',stagnant_rounds=s['stagnant_rounds'],next_controller_monotonic_start=end,active_jobs=[],recorded_at=time.time(),current_turn_classification='Progress: two controlled tangent fits completed; nontrivial native portability, fixed objective and input identity verified; three frozen failure animations produced. Development and promotion pending.',previous_turn_classification='Progress: context diagnosis and observed tangent feature contracts completed.',blocked_audit=dict(consecutive_goal_turns=0,condition=None),work_accounting='Parent active-work interval recorded once; no child runtime added.',pending_source_revisions={},pending_document_revisions={})
 cp['latest_live_observation']=dict(training=dict(session_id=65650,terminal=True,exit_code=0,fits=2),visuals=dict(session_id=51565,terminal=True,exit_code=0),portability=dict(parent_exit_code=0,native_exit_code=3221225477,assertions_passed=True))
 cp['next_safe_actions']=['All jobs terminal. Run frozen evaluate_sequence_tangent_v2.py using sequence_tangent_evaluation_plan_v2.json; both models must be frozen before validation. No restart or additional fit.','Require exact original procedural-control reproduction and all old/new/combined quality gates for both seeds. Preserve failures; no favorable-seed selection.','Keep six confirmation clips absent. Native actual-trained-weight workflows and human usability remain separate requirements if development passes.','Preserve0.19.1archive,full endpoint,100evaluation ceiling,deadline1789053845,data/compute limits,original floors and deferrals.','Use frozen prior-model visual comparisons as research inspection only; no independent human assessment or Cascadeur comparison inferred.','Prepared profile_private_phases_v1.py remains unexecuted. Run only when training, evaluation and other task-owned host jobs are terminal; it measures stage stalls without changing production code.']
 write(base+'checkpoint-tangent-training-v1.json',cp);print(dict(round=63,remaining_evaluations=37,prior_artifacts=len(read(previous)['artifacts']),artifact_count=len(paths),work_seconds=duration,fits=fits,all_jobs_terminal=True,full_goal_complete=False))
if __name__=='__main__':main()
