"""Record broader real-rig continuity evidence under the same full goal."""
import copy,time
from checkpoint_expanded_goal_v19 import ROOT,read,write,sha,g
from evaluate_milestone_goal_v2 import evaluate

def main():
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/'
 cp=read(base+'checkpoint-shape-curves-v1.json');prior=cp['state_path'];old=read(prior);s=copy.deepcopy(old);previous=cp['evidence'];e=read(previous)
 dest=gp+'01a073fe-c240-70c0-b5cd-fe9653aac60e-broader-shape-v1.json';assert not (ROOT/dest).exists();assert cp['round']==55 and s['contract']['max_goalposts']==75 and cp['deadline_unix']==1788981845.
 changed=[n for n,h in e['artifacts'].items() if sha(n)!=h];assert not changed,changed
 comparison=read(res+'broader-shape-comparison-v1.json');assert comparison['complete'] and len(comparison['rows'])==6 and len(comparison['crouch_regression'])==3 and comparison['native_lifecycle_cases']==4 and comparison['fresh_reload_cases']==6
 runtime={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT)) for p in (ROOT/'b4artists_ml').glob('*.py')};assert runtime==read(base+'package-test-v0.18.0.json')['runtime_sha256']==comparison['runtime_sha256'] and sha(cp['artifact']['path'])==cp['artifact']['sha256']
 for folder in ('broader-shape-workflow-v1','broader-shape-workflow-v2','broader-shape-reload-v1','shape-aware-crouch-v1'):
  processes=read(res+folder+'/processes.json');assert len(processes)==3 and all(r['complete'] for r in processes)
 inputs=[tr+n for n in ('shape_aware_contacts_v1.py','check_broader_shape_workflow_v1.py','check_broader_shape_workflow_v2.py','verify_broader_shape_reload_v1.py','check_shape_aware_crouch_v1.py','finalize_broader_shape_v1.py','checkpoint_broader_shape_v1.py')]+['tests/test_b4artists_ml_shape_aware_contacts_v1.py',base+'BROADER-SHAPE-RESEARCH-v1.md']
 added=[n for n in inputs if n not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract']);a=copy.deepcopy(s['contract']);b=copy.deepcopy(old['contract']);a.pop('inputs');b.pop('inputs');assert a==b
 s['explicit_revisions'].append(dict(reason='Six reach/hold and mechanical root-yaw references expose post-smoothing contact errors. Research cubic-aware validation passes after one turn refinement with original limits;4native lifecycle cases,6fresh reload cases,3prior crouch regressions pass. Runtime remains0.18.0; original endpoint,75ceiling,deadline,floors/history unchanged.',prior_state=prior,prior_sha256=sha(prior),prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],added_inputs=added,recorded_at=time.time()))
 paths=set(e['artifacts'])|set(inputs)|{prior,previous,gp+'broader-shape-routing-v1.json',gp+'broader-shape-review-v1.json',res+'broader-shape-comparison-v1.json',res+'broader-shape-source-audit-v1.json',res+'shape-aware-contacts-v1-test_b4artists_ml_shape_aware_contacts_v1.json',res+'shape-aware-contacts-v1-regression.json',tr+'cache/shape-aware-contacts-v1-test_b4artists_ml_shape_aware_contacts_v1.log'}
 for folder in ('broader-shape-workflow-v1','broader-shape-workflow-v2','broader-shape-reload-v1','shape-aware-crouch-v1'):paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/folder).rglob('*') if p.is_file())
 data_plan=read(tr+'temporal_expansion_plan_v19.json');assert all(not (ROOT/tr/'cache'/(n+'.bvh')).exists() for n in data_plan['planned_splits']['confirmation'])
 fp=g.fingerprint(ROOT,s['contract']['inputs']);e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={n:sha(n) for n in sorted(paths)},previous_evidence_recheck=dict(path=previous,sha256=sha(previous),changed_artifacts=[],all_prior_artifacts_unchanged=True),broader_shape_research=comparison)
 e['qualification'].update(priority_continuity_research=True,full_sequence_continuity=False,full_humanoid_workflow=False,temporal_model_qualification=False,independent_usability='unknown',full_goal_complete=False)
 ep=gp+'broader-shape-evidence-v1.json';write(ep,e);obs=read(gp+'shape-curves-observations-v1.json')
 for group in obs.values():
  for row in group.values():row.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 op=gp+'broader-shape-observations-v1.json';write(op,obs);end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];assert duration>=0;g.record_work(s,'controller-broader-shape-v1',duration);result=evaluate(s,obs,ROOT)
 assert result['round']==56 and result['decision']=='iterate' and s['history'][:-1]==old['history'] and s['floors']==old['floors'] and s['passed_checks']==old['passed_checks'] and s['passed_progress_milestones']==old['passed_progress_milestones']
 result['evidence_transport_note']='Authenticated assessment and independent review remain unavailable; broader real-rig contact and continuity evidence retained, full endpoint and prior floors unchanged.';s['history'][-1]=result;write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result)+'\n\n'+result['evidence_transport_note']+'\n',encoding='utf-8')
 cp.update(state_path=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=56,remaining_evaluations=19,evidence=ep,decision='iterate',stagnant_rounds=s['stagnant_rounds'],next_controller_monotonic_start=end,active_jobs=[],recorded_at=time.time(),current_turn_classification='Progress:6new reach/hold and mechanical yaw scenes pass cubic-aware contacts,6fresh reload/source recovery cases,4native lifecycle checks and3crouch regressions pass; original limits unchanged. Runtime0.18.0unchanged.',blocked_audit=dict(consecutive_goal_turns=0,condition=None),work_accounting='Recorded controller-broader-shape-v1 parent interval once; child durations not added.')
 cp['next_safe_actions']=['Integrate opt-in bounded curve smoothing into authored runtime generation with complete rollback and explicit unsupported-representation rejection.','Contact correction for smoothed authored candidates must validate the smoothed output and adaptively refine; preserve original tolerances and four-refinement cap.','Run current-runtime regression, source-preserving cancellation/setting-change checks and exact package tests before a new local installer.','Preserve original full learned goal,75total evaluations,existingdeadline,andpendingindependentanimator assessment.']
 cp['latest_live_observation']={name:dict(session_id=session,terminal=True,exit_code=0) for name,session in [('broader_original',60169),('broader_shape_aware',7744),('native_lifecycle',89945),('crouch_regression',86360),('fresh_reload',81970)]}
 write(base+'checkpoint-broader-shape-v1.json',cp);print(dict(round=56,remaining_evaluations=19,new_reference_cases=6,native_lifecycle_cases=4,fresh_reload_cases=6,crouch_regression_cases=3,prior_artifacts_checked=len(read(previous)['artifacts']),artifacts=len(paths),work_seconds=duration,runtime_unchanged=True,full_goal_complete=False))
if __name__=='__main__':main()
