"""Record exact0.19.0 runtime/package evidence under the unchanged full goal."""
import copy,time,zipfile
from checkpoint_expanded_goal_v19 import ROOT,read,write,sha,g
from evaluate_milestone_goal_v2 import evaluate

def main():
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/'
 cp=read(base+'checkpoint-limit100-plus20h-v1.json');prior=cp['state_path'];old=read(prior);s=copy.deepcopy(old);previous=cp['evidence'];e=read(previous)
 dest=gp+'01a073fe-c240-70c0-b5cd-fe9653aac60e-shape-runtime-v1.json';assert not (ROOT/dest).exists();assert cp['round']==56 and s['contract']['max_goalposts']==100 and cp['deadline_unix']==1789053845.
 originals=read(res+'shape-runtime-baseline-v1/receipt.json');changed=[n for n,h in e['artifacts'].items() if sha(n)!=h];assert set(changed)==set(originals),changed;versions={}
 for n in changed:
  item=originals[n];assert sha(item['prior_version'])==item['before_sha256']==e['artifacts'][n];versions[n]=dict(path=item['prior_version'],sha256=item['before_sha256'])
 meta=read(base+'package-test-v0.19.0.json');offline=read(res+'shape-runtime-package-v1.json');rows=read(res+'shape-runtime-full-v1-regression.json');runtime={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT)) for p in (ROOT/'b4artists_ml').glob('*.py')}
 assert read(res+'shape-runtime-finalization-v1.json')['complete'] and meta['ready_for_local_testing'] and meta['runtime_sha256']==offline['runtime_sha256']==runtime and len(rows)==40 and sum(r['tests'] for r in rows)==398
 for r in rows:assert r['assertions_passed'] and not r['failures'] and not r['errors'] and not r['skipped'] and r['runtime_sha256']==runtime and sha(r['log'])==r['sha256']
 assert offline['passed'] and offline['cases']==13 and offline['offline_guard_self_test'] and not offline['denied_runtime_calls'] and offline['package_sha256']==meta['sha256']==sha('releases/b4artists_ml_v0.19.0.zip');assert sum(r.get('contact_checks',0) for r in offline['records'])==9813
 with zipfile.ZipFile(ROOT/'releases/b4artists_ml_v0.19.0.zip') as z:assert len(z.namelist())==41 and all(z.read(n)==(ROOT/n).read_bytes() for n in z.namelist())
 for profile in ('boneforge','rigify_basic','rigify_default'):
  d=read(res+'broader-shape-runtime-v1/'+profile+'/report.json');assert d['complete'] and d['runtime_sha256']==runtime
  for case in d['cases']:
   assert case['source_restored'] and case['anchor_payloads_unchanged'];r=case['variants'][0];assert r['research_numerical_match'] and r['contact_gate_passed'] and r['priority_gate_passed'] and sha(r['scene'])==r['scene_sha256']
  d=read(res+'humanoid-workflow-review-v7-shape/'+profile+'/report.json');assert d['full_humanoid_workflow_passed'] and d['runtime_sha256']==runtime and d['source_restored'] and d['keep_restore_passed']
 inputs=['b4artists_ml/curve_smoothing.py']+[tr+n for n in ('shape_runtime_regression_plan_v1.json','check_broader_shape_runtime_v1.py','build_humanoid_workflow_review_v7.py','build_shape_runtime_package_v1.py','check_shape_runtime_package_v1.py','finalize_shape_runtime_package_v1.py','checkpoint_shape_runtime_v1.py')]+['tests/'+n for n in ('test_b4artists_ml_curve_smoothing_math_v1.py','test_b4artists_ml_curve_smoothing_native_v1.py','test_b4artists_ml_smoothed_contacts_v1.py','test_b4artists_ml_smoothed_preview_v1.py','test_b4artists_ml_smoothed_preview_v2.py')]+[base+'SMOOTH-TRANSITIONS-v0.19.0.md',base+'ARCHITECTURE-REASSESSMENT-v1.md']
 added=[n for n in inputs if n not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract']);a=copy.deepcopy(s['contract']);b=copy.deepcopy(old['contract']);a.pop('inputs');b.pop('inputs');assert a==b
 s['explicit_revisions'].append(dict(reason='Optional smooth authored runtime and cubic-aware contact validation integrated.398native and13exact-packageofflineworkflows pass;6broaderreferences match research and3crouch workflows pass. Preserve original full learned endpoint,100ceiling,deadline,floors/history; source/document prior versions retained.',prior_state=prior,prior_sha256=sha(prior),prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],added_inputs=added,preserved_prior_versions=versions,recorded_at=time.time()))
 paths=set(e['artifacts'])|set(inputs)|{prior,previous,base+'package-test-v0.19.0.json','releases/b4artists_ml_v0.19.0.zip',gp+'shape-runtime-routing-v1.json',gp+'shape-runtime-review-v1.json',res+'shape-runtime-source-audit-v1.json',res+'shape-runtime-finalization-v1.json',res+'shape-runtime-full-v1-regression.json',res+'shape-runtime-package-v1.json',res+'shape-runtime-package-v1-process.json',tr+'cache/shape-runtime-package-v1.log'}
 for folder in ('shape-runtime-baseline-v1','broader-shape-runtime-v1','humanoid-workflow-review-v7-shape'):paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/folder).rglob('*') if p.is_file())
 for r in rows:paths.add(r['log'].replace('\\','/'));paths.add(res+'shape-runtime-full-v1-'+r['suite']+'.json')
 for prefix in ('shape-runtime-new-v1','shape-runtime-preview-v2'):
  paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res).glob(prefix+'*.json'));paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/tr/'cache').glob(prefix+'*.log'))
 data_plan=read(tr+'temporal_expansion_plan_v19.json');assert all(not (ROOT/tr/'cache'/(n+'.bvh')).exists() for n in data_plan['planned_splits']['confirmation'])
 fp=g.fingerprint(ROOT,s['contract']['inputs']);e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={n:sha(n) for n in sorted(paths)},previous_evidence_recheck=dict(path=previous,sha256=sha(previous),changed_artifacts=changed,preserved_prior_versions=versions,all_other_prior_artifacts_unchanged=True),shape_runtime_package=dict(metadata=meta,offline=offline,full_regression_cases=398,host_exit_qualified=False,installed=False,published=False))
 e['qualification'].update(current_source_full_regression=True,current_package_matches_worktree=True,packaged_authored_workflow=True,smoothed_authored_workflow=True,full_sequence_continuity=False,temporal_model_qualification=False,independent_usability='unknown',full_humanoid_workflow=False,full_goal_complete=False)
 ep=gp+'shape-runtime-evidence-v1.json';write(ep,e);obs=read(gp+'broader-shape-observations-v1.json')
 for group in obs.values():
  for row in group.values():row.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 op=gp+'shape-runtime-observations-v1.json';write(op,obs);end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];g.record_work(s,'controller-shape-runtime-v1',duration);result=evaluate(s,obs,ROOT)
 assert result['round']==57 and result['decision']=='iterate' and s['history'][:-1]==old['history'] and s['floors']==old['floors'] and s['passed_checks']==old['passed_checks'] and s['passed_progress_milestones']==old['passed_progress_milestones']
 result['evidence_transport_note']='Authenticated goal assessment and independent review remain unavailable. Raw398native and13offline results preserved; original floors and full endpoint unchanged.';s['history'][-1]=result;write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result)+'\n\n'+result['evidence_transport_note']+'\n',encoding='utf-8')
 cp.update(state_path=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=57,remaining_evaluations=43,evidence=ep,decision='iterate',stagnant_rounds=s['stagnant_rounds'],next_controller_monotonic_start=end,active_jobs=[],pending_source_revisions={},pending_document_revisions={},recorded_at=time.time(),work_accounting='Recorded controller-shape-runtime-v1 parent interval once; child durations not added.',current_turn_classification='Progress: optional smooth authored motion and cubic-aware contacts integrated in0.19.0localarchive;398native and13offlineworkflows pass;6reference matches and3crouch workflows. Fulllearnedgoal andhumanusability remainincomplete.',blocked_audit=dict(consecutive_goal_turns=0,condition=None))
 cp['artifact']=dict(path='releases/b4artists_ml_v0.19.0.zip',sha256=meta['sha256'],files=41,bytes=meta['bytes'],matches_current_source=True,experimental=True,note='Exact archive passes398native and13offlineworkflows; current viewport and learned temporal quality remain unqualified.')
 cp['next_safe_actions']=['Profile isolated default-Rigify generation and publication with smoothing on/off; overlapping runs showed slices up to0.74seconds, so responsiveness remains unqualified. Optimize the measured bottleneck while preserving exact candidate/source recovery.','Follow ARCHITECTURE-REASSESSMENT-v1.md: prospectively plan a bounded compact temporal versus conditional diffusion comparison, with canonical motion representation, data-rights/coverage audit and fixed compute/latency budgets before fitting; keep sealed confirmation untouched.','Evaluate larger timing/proportion and bound-mesh behavior with actual rigs; keep procedural and learned evidence separate.','Keep repeated selector fitting paused. Broaden natural locomotion and airborne evaluation without weakening old gates; require human usability and equivalent Cascadeur comparison before parity claims.','Preserve100total evaluations,existingdeadline,andpendingindependentanimator assessment.']
 cp['latest_live_observation']={'native_regression':dict(session_id=7570,terminal=True,exit_code=0),'runtime_references':dict(session_id=4714,terminal=True,exit_code=0),'runtime_crouch':dict(session_id=68763,terminal=True,exit_code=0),'exact_package':dict(session_id=82802,terminal=True,exit_code=0)}
 write(base+'checkpoint-shape-runtime-v1.json',cp);print(dict(round=57,remaining_evaluations=43,native_cases=398,offline_cases=13,artifact=cp['artifact']['path'],sha256=meta['sha256'],work_seconds=duration,prior_artifacts_checked=len(read(previous)['artifacts']),artifact_count=len(paths),full_goal_complete=False))
if __name__=='__main__':main()
