"""Record measured feasibility, a corrected representation and live bounded fits."""
import copy,time
from checkpoint_expanded_goal_v19 import ROOT,read,write,sha,g
from evaluate_milestone_goal_v2 import evaluate

def main():
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/';cp=read(base+'checkpoint-shape-runtime-v1.json');old=read(cp['state_path']);s=copy.deepcopy(old);previous=cp['evidence'];e=read(previous);assert cp['round']==57 and s['contract']['max_goalposts']==100 and cp['deadline_unix']==1789053845.
 for n,h in e['artifacts'].items():assert sha(n)==h,n
 profile=read(res+'shape-isolated-profile-v1/report.json');stage=read(res+'sequence-feasibility-v2/report.json');host=read(res+'sequence-portability-v2/host.json');corpus=read(res+'sequence-corpus-v2/manifest.json');tests=read(res+'sequence-portability-v2/request-tests.json')
 assert profile['complete'] and len(profile['runs'])==5 and stage['complete'] and host['complete'] and len(host['cases'])==6 and corpus['complete'] and corpus['window_count']==5778 and tests['passed'] and tests['tests']==18
 runtime={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT)) for p in (ROOT/'b4artists_ml').glob('*.py')};assert profile['runtime_sha256']==runtime==read(base+'package-test-v0.19.0.json')['runtime_sha256']
 names=['profile_shape_isolated_v1.py','sequence_feasibility_plan_v1.json','sequence_feasibility_plan_v2.json','sequence_corpus_plan_v1.json','sequence_corpus_plan_v2.json','sequence_conditioning_v1.py','sequence_model_v1.py','sequence_numpy_v1.py','sequence_packet_v2.py','sequence_provider_v2.py','check_sequence_feasibility_v1.py','check_sequence_feasibility_v2.py','check_sequence_portability_v1.py','check_sequence_portability_v2.py','build_sequence_corpus_v1.py','build_sequence_corpus_v2.py','train_sequence_corpus_v1.py','train_sequence_corpus_v2.py','checkpoint_sequence_feasibility_v2.py']
 inputs=[tr+n for n in names]+['tests/'+n for n in ('test_b4artists_ml_sequence_conditioning_v1.py','test_b4artists_ml_sequence_packet_v2.py','test_b4artists_ml_sequence_provider_v2.py')]+[base+'SEQUENCE-FEASIBILITY-v1.md',base+'SEQUENCE-FEASIBILITY-v2.md'];added=[n for n in inputs if n not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract']);a=copy.deepcopy(s['contract']);b=copy.deepcopy(old['contract']);a.pop('inputs');b.pop('inputs');assert a==b
 s['explicit_revisions'].append(dict(reason='Measured native bottleneck and established canonical sequence-learning/export feasibility. Raw-rotation preparation mismatch stopped and retained; shared encoder and18checks now pass. Same endpoint,100ceiling,deadline,history/floors; no runtime promotion.',prior_state=cp['state_path'],prior_sha256=sha(cp['state_path']),added_inputs=added,prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],recorded_at=time.time()))
 paths=set(e['artifacts'])|set(inputs)|{cp['state_path'],previous}
 for folder in ('shape-isolated-profile-v1','sequence-feasibility-v1','sequence-feasibility-v2','sequence-portability-v1','sequence-portability-v2','sequence-corpus-v1','sequence-corpus-v2','sequence-corpus-training-v1'):
  paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/folder).rglob('*') if p.is_file())
 paths.update(gp+n for n in ('sequence-feasibility-routing-v1.json','sequence-corpus-review-v1.json','sequence-corpus-review-v2.json','sequence-representation-correction-v2.json'))
 plan=read(tr+'temporal_expansion_plan_v19.json');assert all(not (ROOT/tr/'cache'/(n+'.bvh')).exists() for n in plan['planned_splits']['confirmation']);fp=g.fingerprint(ROOT,s['contract']['inputs']);e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={n:sha(n) for n in sorted(paths)},previous_evidence_recheck=dict(path=previous,sha256=sha(previous),all_prior_artifacts_unchanged=True),sequence_feasibility=dict(profile=res+'shape-isolated-profile-v1/report.json',canonical_stage=res+'sequence-feasibility-v2/report.json',native_export_cases=6,request_representation_provider_tests=18,training_windows=5778,training_clips=78,training_complete=False,raw_representation_attempt_rejected=True,full_quality_qualified=False))
 e['qualification'].update(temporal_model_qualification=False,independent_usability='unknown',full_goal_complete=False);ep=gp+'sequence-feasibility-evidence-v2.json';write(ep,e);obs=read(gp+'shape-runtime-observations-v1.json')
 for group in obs.values():
  for row in group.values():row.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 op=gp+'sequence-feasibility-observations-v2.json';write(op,obs);end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];g.record_work(s,'controller-sequence-feasibility-v2',duration);result=evaluate(s,obs,ROOT)
 assert result['round']==58 and result['decision']=='iterate' and s['history'][:-1]==old['history'] and s['floors']==old['floors'];result['evidence_transport_note']='Authenticated assessment and independent review unavailable. Canonical data/learning/native inference evidence recorded; actual full motion quality remains unqualified.';s['history'][-1]=result;dest=gp+'01a073fe-c240-70c0-b5cd-fe9653aac60e-sequence-feasibility-v2.json';assert not (ROOT/dest).exists();write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result)+'\n\n'+result['evidence_transport_note']+'\n',encoding='utf-8')
 cp.update(state_path=dest,last_evaluated_state=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=58,remaining_evaluations=42,evidence=ep,decision='iterate',stagnant_rounds=s['stagnant_rounds'],next_controller_monotonic_start=end,active_jobs=[dict(kind='unified_exec',session_id=61813,task='Four canonical corpus fits: direct/diffusion x2seeds',process_registry=res+'sequence-corpus-training-v2/active-process.json')],recorded_at=time.time(),previous_turn_classification='Progress:0.19.0exactpackage finalized and architecture reassessment recorded.',current_turn_classification='Progress:isolated native profile,canonical sequence models/export tests,corrected training data and live fixed corpus fits. No full quality or completion claim.',blocked_audit=dict(consecutive_goal_turns=0,condition=None),work_accounting='Recorded parent active-work interval once; child runtime not added.')
 cp['latest_live_observation']=dict(training=dict(session_id=61813,live_verified=True,completed_at_least_epochs=3),raw_training=dict(session_id=64470,terminal=True,exit_code=1),canonical_corpus=dict(session_id=67740,terminal=True,exit_code=0),profile=dict(session_id=38914,terminal=True,exit_code=0))
 cp['next_safe_actions']=['Revalidate unified session61813 and its exact child process; preserve same job on observation timeouts. Four fixed60epoch fits,1800seconds per fit.','Once all canonical fits finish, freeze weights and evaluate all unchanged old/new/combined development gates against existing projected linear/Hermite/shape controls. Use sequence_provider_v2 and semantic_projection; retain masked context and exact priorities.','Do not promote one-clip feasibility weights or rejected raw-rotation corpus. Same5778windows in corrected corpus; no validation/confirmation read yet.','Investigate private working-rig sequence projection to reduce measured source restoration/guard overhead, preserving source/cancel/final-rig equivalence.','Preserve100total evaluations,extendeddeadline,paused selector variations,full original endpoint and pending independent animator assessment.']
 write(base+'checkpoint-sequence-feasibility-v2.json',cp);print(dict(round=58,remaining_evaluations=42,prior_artifacts_verified=len(read(previous)['artifacts']),artifact_count=len(paths),work_seconds=duration,active_training_session=61813,full_goal_complete=False))
if __name__=='__main__':main()
