"""Preserve the tested0.19.1package and completed frozen-model diagnosis."""
import copy,time
from checkpoint_expanded_goal_v19 import ROOT,read,write,sha,g
from evaluate_milestone_goal_v2 import evaluate

def main():
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/';cp=read(base+'checkpoint-private-production-v1.json');old=read(cp['state_path']);s=copy.deepcopy(old);previous=cp['evidence'];e=read(previous)
 assert cp['round']==60 and s['contract']['max_goalposts']==100 and cp['deadline_unix']==1789053845.
 final=read(res+'private-runtime-finalization-v1.json');revisions=final['document_revisions'];changed={n for n,h in e['artifacts'].items() if sha(n)!=h};assert changed==set(revisions),changed
 for n,v in revisions.items():assert sha(v['prior_version'])==v['before_sha256']==e['artifacts'][n] and sha(n)==v['after_sha256']
 meta=read(base+'package-test-v0.19.1.json');offline=read(res+'private-runtime-package-v1.json');runtime={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT)) for p in (ROOT/'b4artists_ml').glob('*.py')}
 assert meta['ready_for_local_testing'] and offline['passed'] and offline['cases']==13 and not offline['denied_runtime_calls'] and meta['runtime_sha256']==offline['runtime_sha256']==runtime==final['runtime_sha256']
 assert sha('releases/b4artists_ml_v0.19.1.zip')==meta['sha256']==offline['package_sha256']
 diagnosis=read(res+'sequence-projection-diagnosis-v1/report.json');assert diagnosis['complete'] and diagnosis['stored_projection_metrics_reproduced'] and diagnosis['models_unchanged'] and not diagnosis['retraining'] and not diagnosis['confirmation_read']
 assert all(v['position']['raw']>1 for v in diagnosis['ratios_to_stage_best_control']['combined'].values())
 inputs=[tr+n for n in ('finalize_private_runtime_package_v1.py','diagnose_sequence_projection_v1.py','checkpoint_private_package_v1.py')]+[base+'PRIVATE-GENERATION-v0.19.1.md',base+'SEQUENCE-PROJECTION-DIAGNOSIS-v1.md'];added=[n for n in inputs if n not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract']);a=copy.deepcopy(s['contract']);b=copy.deepcopy(old['contract']);a.pop('inputs');b.pop('inputs');assert a==b
 s['explicit_revisions'].append(dict(reason='Exact0.19.1offline archive and documentation finalized. Frozen raw/projected diagnosis confirms learned predictions already fail before projection. Same endpoint, limits, floors and history; no new fit or temporal promotion.',prior_state=cp['state_path'],prior_sha256=sha(cp['state_path']),added_inputs=added,document_revisions=revisions,prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],recorded_at=time.time()))
 paths=set(e['artifacts'])|set(inputs)|{cp['state_path'],previous,gp+'private-finalization-routing-v1.json',res+'private-runtime-finalization-v1.json',res+'private-runtime-package-v1.json',res+'private-runtime-package-v1-process.json',tr+'cache/private-runtime-package-v1.log'}|{v['prior_version'] for v in revisions.values()}
 paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/'sequence-projection-diagnosis-v1').rglob('*') if p.is_file())
 paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/tr/'cache/private-runtime-package-v1').rglob('*') if p.is_file())
 assert all(not (ROOT/tr/'cache'/(n+'.bvh')).exists() for n in read(tr+'temporal_expansion_plan_v19.json')['planned_splits']['confirmation'])
 fp=g.fingerprint(ROOT,s['contract']['inputs']);e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={n:sha(n) for n in sorted(paths)},previous_evidence_recheck=dict(path=previous,sha256=sha(previous),all_unrevised_artifacts_unchanged=True,document_revisions=revisions),private_package=dict(native_cases=408,offline_cases=13,archive_version='0.19.1',archive_verification_passed=True,standalone_verified=True,raw_projected_diagnosis=res+'sequence-projection-diagnosis-v1/report.json',temporal_model_qualified=False,full_goal_complete=False))
 e['qualification'].update(temporal_model_qualification=False,independent_usability='unknown',full_goal_complete=False);ep=gp+'private-package-evidence-v1.json';write(ep,e);obs=read(gp+'private-production-observations-v1.json')
 for group in obs.values():
  for row in group.values():row.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 op=gp+'private-package-observations-v1.json';write(op,obs);end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];g.record_work(s,'controller-private-package-v1',duration);result=evaluate(s,obs,ROOT)
 assert result['round']==61 and result['decision']=='iterate' and s['history'][:-1]==old['history'] and s['floors']==old['floors'];result['evidence_transport_note']='Authenticated assessment and independent review unavailable. Completed archive and causal diagnostic recorded; full learned motion/human usability/Cascadeur endpoint remains incomplete.';s['history'][-1]=result;dest=gp+'01a073fe-c240-70c0-b5cd-fe9653aac60e-private-package-v1.json';assert not (ROOT/dest).exists();write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result)+'\n\n'+result['evidence_transport_note']+'\n',encoding='utf-8')
 cp.update(state_path=dest,last_evaluated_state=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=61,remaining_evaluations=39,evidence=ep,decision='iterate',stagnant_rounds=s['stagnant_rounds'],next_controller_monotonic_start=end,active_jobs=[],recorded_at=time.time(),current_turn_classification='Progress:0.19.1exact archive finalized, current documentation updated, raw/projected diagnosis rejects projection-only explanation. No new model fit or promotion.',blocked_audit=dict(consecutive_goal_turns=0,condition=None),work_accounting='Parent active-work interval recorded once; no child runtime added.',pending_source_revisions={},pending_document_revisions={})
 cp['artifact'].update(ready_for_local_testing=True,note='408native tests and13exact offline workflows; default-Rigify reference work reduced40.9% with exact curves. Full motion quality and viewport responsiveness unqualified.')
 cp['latest_live_observation']=dict(package=dict(session_id=3301,terminal=True,parent_exit_code=0,host_exit_code=3221225477,cases=13,passed=True),projection_diagnosis=dict(session_id=4739,terminal=True,exit_code=0,windows=768,models_unchanged=True))
 cp['next_safe_actions']=['All tracked jobs are terminal. Preserve finalized0.19.1archive and documentation; do not rerun completed suites without a new change or failure.','Establish the next bounded generalization/conditioning hypothesis before any fit. Both direct seeds learn training examples but all four models already fail raw development position/velocity/acceleration ratios. Projection slightly improves position; do not weaken it.','Initial-root orientation canonicalization already exists in rig_observations.encode; do not duplicate it. Explicit contact/style/physical context remains absent and must be derived from actual authored workflow requirements.','Preserve100ceiling,extendeddeadline,full endpoint,original acceptance gates,sealed confirmation,data/compute limits and existing deferrals.','Human usability and equivalent Cascadeur comparison remain pending; do not fabricate assessments or repeat the unanswered request.']
 cp['publication'].update(head='3153a8946fd8ef1415d9901c30a56bcc6783c49d axlbot <axleonex@gmail.com> axlbot <axleonex@gmail.com>',tracked_diff_empty=True,index_empty=True,committed=False,pushed=False,installed=False)
 write(base+'checkpoint-private-package-v1.json',cp);print(dict(round=61,remaining_evaluations=39,prior_artifacts=len(read(previous)['artifacts']),document_revisions=len(revisions),artifact_count=len(paths),work_seconds=duration,all_jobs_terminal=True,full_goal_complete=False))
if __name__=='__main__':main()
