"""Record rejected optimizations and exact release restoration under the same goal."""
import copy,time,subprocess,zipfile
from pathlib import Path
from checkpoint_expanded_goal_v19 import ROOT,read,sha,write,g,evaluate

def main():
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/';prefix='01a073fe-c240-70c0-b5cd-fe9653aac60e-';prior=gp+prefix+'component-diagnosis-v25.json';dest=gp+prefix+'pruning-experiments-v1.json';assert not (ROOT/dest).exists();old=read(prior);s=copy.deepcopy(old);cp=read(base+'checkpoint-component-diagnosis-v25.json');prev_ev=gp+'component-diagnosis-evidence-v25.json';e=read(prev_ev)
 benches=[read(res+f'pruning-benchmark-v{v}.json') for v in [1,3]]
 for b in benches:assert b['complete'] and not b['passed'] and all(x['exact_pose_signature_metrics_parity'] and x['source_preserved'] for x in b['comparisons'])
 assert not read(res+'pruning-benchmark-v2.json')['complete']
 for v in [1,3]:assert read(res+f'pruning-rejection-v{v}.json')['candidate_rejected']
 isolated=read(res+'restored-proxy-isolation-v1-regression.json');assert len(isolated)==1 and isolated[0]['assertions_passed'] and isolated[0]['tests']==1 and not isolated[0]['skipped']
 meta=read(base+'package-test-v0.17.4.json');current={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT)) for p in (ROOT/'b4artists_ml').glob('*.py')};assert current==meta['runtime_sha256']==isolated[0]['runtime_sha256'];assert sha('releases/b4artists_ml_v0.17.4.zip')==meta['sha256']
 with zipfile.ZipFile(ROOT/'releases/b4artists_ml_v0.17.4.zip') as z:assert all(z.read(n)==(ROOT/n).read_bytes() for n in z.namelist())
 changed=[p for p,h in e['artifacts'].items() if sha(p)!=h];assert set(changed)=={base+n+'.md' for n in ['PROJECT','ROADMAP','REQUIREMENTS']},changed;versions={}
 for p in changed:
  snapshot=res+'pruning-document-baseline-v1/'+Path(p).name;assert sha(snapshot)==e['artifacts'][p];versions[p]=dict(path=snapshot,sha256=sha(snapshot))
 names=['pruning_plan_v1.json','pruning_plan_v2.json','pruning_regression_plan_v1.json','benchmark_pruning_v1.py','benchmark_pruning_v2.py','benchmark_pruning_v3.py','checkpoint_pruning_goal_v1.py'];inputs=[tr+n for n in names]+[base+'PRUNING-EXPERIMENTS-v1.md','tests/test_b4artists_ml_proxy_isolation.py'];added=[p for p in inputs if p not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract']);s['explicit_revisions'].append(dict(reason='Record two rejected pruning optimizations, native-context correction evidence and exact0.17.4restoration. Add retained source-isolation regression. Original endpoint, floors/milestones,50total evaluations and fixed15-hour deadline unchanged.',prior_state=prior,prior_sha256=sha(prior),prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],added_inputs=added,recorded_at=time.time()));fp=g.fingerprint(ROOT,s['contract']['inputs'])
 paths=set(e['artifacts'])|set(inputs)|{prior,prev_ev,gp+'pruning-routing-v1.json',gp+'pruning-routing-v2.json'}
 for pattern in ['pruning-*.json','bulk-pruning-*.json','restored-proxy-isolation-v1*.json']:paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res).glob(pattern) if p.is_file())
 for pattern in ['pruning-benchmark-*.log','bulk-pruning-*.log','restored-proxy-isolation-v1*.log']:paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/tr/'cache').glob(pattern) if p.is_file())
 for folder in ['pruning-runtime-baseline-v1','pruning-rejected-v1','pruning-context-failure-v2','pruning-rejected-v3','pruning-document-baseline-v1']:paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/folder).glob('*') if p.is_file())
 plan=read(tr+'temporal_expansion_plan_v19.json');assert all(not (ROOT/tr/'cache'/(c+'.bvh')).exists() for c in plan['planned_splits']['confirmation'])
 e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={p:sha(p) for p in sorted(paths)},previous_evidence_recheck=dict(path=prev_ev,sha256=sha(prev_ev),changed_artifacts=changed,preserved_prior_versions=versions,all_other_prior_artifacts_unchanged=True),pruning_comparisons=[b['comparisons'] for b in benches],pruning_candidates_rejected=True,pruning_restored_package_exact=True,proxy_source_isolation=isolated,preserved_milestones=old['passed_progress_milestones'],new_passing_milestones=[])
 e['regression'].update(rerun_this_iteration=False,retained_from=prev_ev,note='Exact0.17.4runtime restored; prior330-case/31-suite and four offline checks retained, not rerun. One fresh source-isolation unittest with three rig subcases passes on restored source. Planned331-case full regression was not run after failed speed gates.')
 e['qualification'].update(full_goal_complete=False,temporal_model_qualification=False,temporal_animator_integration=False,host_shutdown=False,independent_usability='unknown',full_physics_acceptance=False,full_responsiveness=False)
 e['limitations']=['Both fixed pruning experiments worsen target pauses despite exact five-profile pose/signature/metric parity; neither is promoted.','Native operator context failures and corrected private-copy source-isolation checks are retained. Runtime0.17.4restored exactly; no new package or full regression claimed.','All original learned workflow, physics/refinement, rig/quadruped, connector, distribution, supported-host lifecycle, responsiveness, independent animator and equivalent Cascadeur requirements remain incomplete.','Host shutdown crash remains; six fresh confirmation clips remain absent.']
 args=['git','-c','safe.directory=X:/Scripting Attempts/B4Artists_Tools/B4Artists_Anim_Tools_github'];assert subprocess.check_output(args+['log','-1','--format=%H %an <%ae> %cn <%ce>'],cwd=ROOT,text=True).strip()==cp['publication']['head'];assert not subprocess.check_output(args+['diff','--name-only'],cwd=ROOT,text=True).strip();assert not subprocess.check_output(args+['diff','--cached','--name-only'],cwd=ROOT,text=True).strip()
 ep=gp+'pruning-experiments-evidence-v1.json';write(ep,e);obs=read(gp+'component-diagnosis-observations-v25.json')
 for group in obs.values():
  for proof in group.values():proof.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 write(gp+'pruning-experiments-observations-v1.json',obs);end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];event='controller-pruning-experiments-v1';assert event not in s['work_events'];g.record_work(s,event,duration);result=evaluate(s,obs,ROOT)
 assert result['round']==41 and result['decision']=='iterate';assert not result['implementation_progress']['new'] and not result['implementation_progress']['lost'];assert all(not c['regression'] for c in result['categories'].values());assert s['history'][:-1]==old['history'];assert cp['max_goalposts']==50 and cp['resumed_run_time_cap_hours']==15 and cp['deadline_unix']==1788902277.2365775
 write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result),encoding='utf-8')
 cp.update(state_path=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=41,remaining_evaluations=9,decision=result['decision'],stagnant_rounds=s['stagnant_rounds'],evidence=ep,active_jobs=[],next_controller_monotonic_start=end,current_turn_classification='Progress: two fixed pruning optimizations tested and rejected for slower ticks; exact0.17.4runtime restored. New source-isolation check passes on three rigs. These results rule out proposed approaches; full original goal remains incomplete.',work_accounting='Recorded controller-pruning-experiments-v1 once from330814.2339832; benchmark69221,9657,15052 and all isolated checks terminal.',next_safe_actions=['Read original objective/checkpoint and current clock; preserve50total evaluations and fixed15-hour deadline21:17:57UTC.','Measure repeated preview decoding before selecting any bounded cache. Preserve independent mutable records, exact-payload invalidation and live structural/target validation; do not infer improvement solely from a profiler.','Keep all learned candidates frozen and six confirmation clips sealed; v24 position-selection failures remain unresolved.','All original workflow/physics/rig/quadruped/connector/distribution and comparative usability requirements remain. Checkpoint at the declared deadline without marking the goal complete.'],recorded_at=time.time());write(base+'checkpoint-pruning-experiments-v1.json',cp);print(dict(round=41,remaining=9,decision=result['decision'],work_seconds=duration,next_controller_monotonic_start=end,full_goal_complete=False))
if __name__=='__main__':main()
