"""Preserve the full goal while recording the failed fixed loss experiment."""
import copy,time,subprocess,zipfile
from pathlib import Path
from checkpoint_expanded_goal_v19 import ROOT,read,sha,write,g,evaluate

def main():
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/'
 prior=gp+'01a073fe-c240-70c0-b5cd-fe9653aac60e-mixture-trajectory-v21.json';dest=prior.replace('mixture-trajectory-v21','relative-mixture-v22');assert not (ROOT/dest).exists()
 old=read(prior);s=copy.deepcopy(old);cp=read(base+'checkpoint-mixture-trajectory-v21.json');prev_ev=gp+'mixture-trajectory-evidence-v21.json';e=read(prev_ev)
 model=read(res+'relative_mixture_v22/report.json');repro=read(res+'relative-mixture-reproduction-v22.json');verification=read(res+'relative-experiment-verification-v22.json');assert verification['passed'] and verification['pre_fit_checks']==9 and repro['passed']
 for n,h in repro['identical_sha256'].items():assert sha(res+'relative_mixture_v22/'+n)==h==sha(res+'relative_mixture_v22_repeat/'+n)
 a=copy.deepcopy(model);b=read(res+'relative_mixture_v22_repeat/report.json')
 for report in [a,b]:report.pop('runtime');report['model_files']={Path(k).name:v for k,v in report['model_files'].items()}
 assert a==b
 previous=read(res+'mixture_trajectory_v21/report.json');assert model['protocol']['gates']==previous['protocol']['gates'] and model['protocol']['projection']==previous['protocol']['projection']
 for part in ['old_validation','new_validation','combined']:
  for name in model['protocol']['baselines']:assert model['partition_reports'][part][name]==previous['partition_reports'][part][name]
 assert all(v['checks']['position'] and not v['checks']['cohorts'] for v in model['development_gates'].values())
 for name,h in model['source_sha256'].items():assert sha(tr+name)==h
 plan=read(tr+'temporal_expansion_plan_v19.json');assert all(not (ROOT/tr/'cache'/(c+'.bvh')).exists() for c in plan['planned_splits']['confirmation']);assert not model['confirmation_read']
 moving=read(res+'relative-mixture-host-v22.json');stationary=read(res+'stationary-relative-host-v22.json');meta=read(base+'package-test-v0.17.4.json')
 current={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT)) for p in (ROOT/'b4artists_ml').glob('*.py')};assert current==meta['runtime_sha256']==moving['runtime_sha256']==stationary['runtime_sha256']
 for host in [moving,stationary]:assert host['complete'] and host['passed'] and len(host['rows'])==16 and host['model_sha256']==model['selection']['best_learned_sha256']
 assert sha('releases/b4artists_ml_v0.17.4.zip')==meta['sha256']
 with zipfile.ZipFile(ROOT/'releases/b4artists_ml_v0.17.4.zip') as z:assert all(z.read(n)==(ROOT/n).read_bytes() for n in z.namelist())
 changed=[p for p,h in e['artifacts'].items() if sha(p)!=h];assert set(changed)=={base+n+'.md' for n in ['PROJECT','ROADMAP','REQUIREMENTS']},changed
 versions={}
 for p in changed:
  snapshot=res+'relative-document-baseline-v22/'+Path(p).name;assert sha(snapshot)==e['artifacts'][p];versions[p]=dict(path=snapshot,sha256=sha(snapshot))
 names=['mixture_diagnosis_plan_v22.json','analyze_mixture_training_v22.py','ablate_mixture_rotations_v22.py','relative_mixture_protocol_v22.json','relative_mixture_v22.py','check_relative_mixture_v22.py','train_relative_mixture_v22.py','check_relative_mixture_host_v22.py','check_stationary_relative_host_v22.py','check_relative_reproduction_v22.py','analyze_relative_result_v22.py','verify_relative_experiment_v22.py','checkpoint_relative_goal_v22.py']
 inputs=[tr+n for n in names]+[base+'RELATIVE-MIXTURE-PLAN-v22.md',base+'RELATIVE-MIXTURE-v22.md'];added=[p for p in inputs if p not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract'])
 s['explicit_revisions'].append(dict(reason='Add training-loss and rotation-ablation diagnosis, one fixed relative cohort loss experiment, compatibility/source audits, exact reproduction and actual-rig recovery. Original endpoint, floors/milestones,50 evaluations and15-hour resumed deadline remain unchanged.',prior_state=prior,prior_sha256=sha(prior),prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],added_inputs=added,recorded_at=time.time()))
 fp=g.fingerprint(ROOT,s['contract']['inputs']);route=gp+'relative-mixture-routing-v22.json';paths=set(e['artifacts'])|set(inputs)|{prior,prev_ev,route}
 for pattern in ['relative-*v22*.json','stationary-relative-host-v22*.json','mixture-training-diagnosis-v22.json','mixture-rotation-ablation-v22.json']:paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res).glob(pattern) if p.is_file())
 for folder in ['relative_mixture_v22','relative_mixture_v22_repeat','relative-document-baseline-v22']:paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/folder).glob('*') if p.is_file())
 for name in ['relative-mixture-host-v22.log','stationary-relative-host-v22.log']:paths.add(tr+'cache/'+name)
 attribution=read(res+'relative-failure-attribution-v22.json');assert attribution['failed']==8 and attribution['prior_failed']==11 and not attribution['newly_failed'];assert model['development_gates']['old_validation']['max_cohort_position_ratio']>previous['development_gates']['old_validation']['max_cohort_position_ratio']
 diagnosis=read(res+'mixture-training-diagnosis-v22.json');ablations=read(res+'mixture-rotation-ablation-v22.json');assert diagnosis['cohorts']==466 and ablations['complete'] and len(ablations['methods'])==3
 e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={p:sha(p) for p in sorted(paths)},previous_evidence_recheck=dict(path=prev_ev,sha256=sha(prev_ev),changed_artifacts=changed,preserved_prior_versions=versions,all_other_prior_artifacts_unchanged=True),learned_host=moving,stationary_host=stationary,temporal_selection=model['selection'],temporal_gates=model['gates'],development_gates=model['development_gates'],reproduction=repro,relative_verification=verification,relative_failure_attribution=attribution,relative_training_diagnosis=diagnosis,relative_rotation_ablations=ablations,preserved_milestones=old['passed_progress_milestones'],new_passing_milestones=[])
 e['regression'].update(rerun_this_iteration=False,retained_from=prev_ev,note='Runtime/package0.17.4 unchanged. Prior330-case/31-suite and four offline package checks retained, not rerun. Nine new weighting checks and32actual-rig cases cover this research candidate;14original predictor checks remain pinned.')
 e['qualification'].update(full_goal_complete=False,temporal_model_qualification=False,temporal_animator_integration=False,host_shutdown=False,independent_usability='unknown',full_physics_acceptance=False,full_responsiveness=False)
 e['limitations']=['Average position gates pass, but worst-cohort gates fail. Failed cohorts decrease11to8while the old worst case worsens1.712to2.451; this is not an overall upgrade or qualification.','Training-label cohort error scales alter fitting weights only. Original feature normalization and inference functions are unchanged, with exact zero-strength fit compatibility.','Three full-development ablations show learned rotations alone do not explain v21average gains. They are exposed diagnostics, not independently qualified alternatives.','All model/non-runtime results reproduce; six fresh confirmation clips remain absent. No data download or temporal model promotion.','32actual-rig checks prove editable results/recovery on existing fixtures, not naturalness or broad production coverage. Host shutdown remains failed.','v0.17.4 runtime/package and historical UI evidence are unchanged. No browser-policy workaround was used.','The original full learned workflow/intent/style/partial-body, physics/refinement, humanoid/quadruped, connector, distribution, responsiveness, supported-host, independent animator and Cascadeur requirements remain.']
 args=['git','-c','safe.directory=X:/Scripting Attempts/B4Artists_Tools/B4Artists_Anim_Tools_github'];assert subprocess.check_output(args+['log','-1','--format=%H %an <%ae> %cn <%ce>'],cwd=ROOT,text=True).strip()==cp['publication']['head'];assert not subprocess.check_output(args+['diff','--name-only'],cwd=ROOT,text=True).strip();assert not subprocess.check_output(args+['diff','--cached','--name-only'],cwd=ROOT,text=True).strip()
 ep=gp+'relative-mixture-evidence-v22.json';write(ep,e);obs=read(gp+'mixture-trajectory-observations-v21.json')
 for group in obs.values():
  for proof in group.values():proof.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 write(gp+'relative-mixture-observations-v22.json',obs)
 end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];event='controller-relative-mixture-v22';assert event not in s['work_events'];g.record_work(s,event,duration);result=evaluate(s,obs,ROOT)
 assert result['round']==37 and result['decision']=='iterate';assert not result['implementation_progress']['new'] and not result['implementation_progress']['lost'];assert all(not c['regression'] for c in result['categories'].values());assert s['history'][:-1]==old['history'];assert cp['max_goalposts']==50 and cp['resumed_run_time_cap_hours']==15 and cp['deadline_unix']==1788902277.2365775
 write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result),encoding='utf-8')
 cp.update(state_path=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=37,remaining_evaluations=13,decision=result['decision'],stagnant_rounds=s['stagnant_rounds'],evidence=ep,active_jobs=[],next_controller_monotonic_start=end,current_turn_classification='Progress: training-loss concentration and three ablations informed a fixed relative-loss model; compatibility/reproduction and32rig checks pass. Eight cohorts fail vs11, but old worst worsens; no promotion and original full goal remains incomplete.',work_accounting='Recorded controller-relative-mixture-v22 once from324677.1852062; sessions16354,29931,21324,85913,26595,77366terminal.',next_safe_actions=['Read original objective/checkpoint; retain50 total evaluations and unchanged15-hour resumed deadline21:17:57UTC.','Keep v21/v22 frozen and six fresh confirmation clips sealed. Loss balancing alone worsens long-gap confidence; investigate observed expert-disagreement/curve-excursion/geometry descriptors in a prospectively fixed next experiment.','Generate parent-dependent training features only from group-excluded parent models, matching their inference calculation. Test feature bounds, hidden-label independence, exact priorities and actual-rig recovery before promotion.','Continue all original full learned workflow, physics/refinement, humanoid/quadruped, optional connector, distribution and responsiveness requirements.','Independent animator and equivalent Cascadeur comparison remain unknown; do not fabricate evidence or bypass browser policy.'],recorded_at=time.time())
 write(base+'checkpoint-relative-mixture-v22.json',cp);progress=read(base+'relative-mixture-progress-v22.json');progress.update(status='evaluated',active_jobs=[],latest_checkpoint=base+'checkpoint-relative-mixture-v22.json',remaining_evaluations=13,rounds_completed=37,recorded_at=time.time());write(base+'relative-mixture-progress-v22.json',progress)
 print(dict(round=37,remaining=13,decision=result['decision'],stagnant_rounds=s['stagnant_rounds'],work_seconds=duration,full_goal_complete=False))
if __name__=='__main__':main()
