"""Preserve context evidence and research contracts without changing the goal."""
import copy,time
from checkpoint_expanded_goal_v19 import ROOT,read,write,sha,g
from evaluate_milestone_goal_v2 import evaluate

def main():
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/';cp=read(base+'checkpoint-private-package-v1.json');old=read(cp['state_path']);s=copy.deepcopy(old);previous=cp['evidence'];e=read(previous)
 assert cp['round']==61 and s['contract']['max_goalposts']==100 and cp['deadline_unix']==1789053845.
 changed={n for n,h in e['artifacts'].items() if sha(n)!=h};assert not changed,changed
 diag=read(res+'sequence-context-audit-v2/report.json');corpus=read(res+'sequence-tangent-corpus-v1/report.json');checks=read(res+'sequence-tangent-contracts-v1/report.json');general=read(res+'sequence-generalization-audit-v1/report.json')
 assert diag['complete'] and diag['request_equivalence']['windows']==1926 and diag['groups']['development']['pairs']==384 and not diag['models_changed'] and not diag['confirmation_read'];assert corpus['complete'] and corpus['windows']==5778 and corpus['condition_prefix_exact'] and corpus['known_observations_exact'] and not corpus['confirmation_read'];assert checks['passed'] and checks['tests']==13 and general['complete']
 assert sha(tr+'sequence_tangent_context_v1.py')==checks['source_sha256']['sequence_tangent_context_v1.py']==read(res+'sequence-tangent-corpus-v1/plan.json')['feature_sha256']
 inputs=[tr+n for n in ('audit_sequence_generalization_v1.py','audit_sequence_context_v1.py','audit_sequence_context_v2.py','sequence_tangent_context_v1.py','sequence_tangent_context_plan_v1.json','check_sequence_tangent_context_v1.py','check_sequence_tangent_corpus_v1.py','checkpoint_sequence_context_v1.py')]+[base+'SEQUENCE-GENERALIZATION-DECISION-v1.md',base+'SEQUENCE-CONTEXT-DIAGNOSIS-v1.md']
 added=[n for n in inputs if n not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract']);a=copy.deepcopy(s['contract']);b=copy.deepcopy(old['contract']);a.pop('inputs');b.pop('inputs');assert a==b
 s['explicit_revisions'].append(dict(reason='Frozen paired context audit shows weak neighboring-motion response; research tangent representation passes analytic and corpus checks. No fitting, promotion, production changes or endpoint change.',prior_state=cp['state_path'],prior_sha256=sha(cp['state_path']),added_inputs=added,prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],recorded_at=time.time()))
 paths=set(e['artifacts'])|set(inputs)|{cp['state_path'],previous,base+'checkpoint-private-package-v1.json',gp+'sequence-generalization-routing-v1.json',gp+'sequence-context-routing-v1.json',gp+'sequence-tangent-routing-v1.json'}
 for folder in ('sequence-generalization-audit-v1','sequence-context-audit-v1','sequence-context-audit-v2','sequence-tangent-contracts-v1','sequence-tangent-corpus-v1'):
  paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/folder).rglob('*') if p.is_file())
 assert all(not (ROOT/tr/'cache'/(n+'.bvh')).exists() for n in read(tr+'temporal_expansion_plan_v19.json')['planned_splits']['confirmation'])
 fp=g.fingerprint(ROOT,s['contract']['inputs']);e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={n:sha(n) for n in sorted(paths)},previous_evidence_recheck=dict(path=previous,sha256=sha(previous),all_artifacts_unchanged=True),motion_context=dict(diagnostic=res+'sequence-context-audit-v2/report.json',training_request_equivalence=1926,paired_training_windows=365,paired_development_windows=384,tangent_contracts=13,tangent_corpus_windows=5778,model_trained=False,temporal_model_qualified=False,full_goal_complete=False))
 e['qualification'].update(temporal_model_qualification=False,independent_usability='unknown',full_goal_complete=False);ep=gp+'sequence-context-evidence-v1.json';write(ep,e);obs=read(gp+'private-package-observations-v1.json')
 for group in obs.values():
  for row in group.values():row.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 op=gp+'sequence-context-observations-v1.json';write(op,obs);end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];g.record_work(s,'controller-sequence-context-v1',duration);result=evaluate(s,obs,ROOT)
 assert result['round']==62 and result['decision']=='iterate' and s['history'][:-1]==old['history'] and s['floors']==old['floors'];result['evidence_transport_note']='Signed assessment and independent review unavailable; concrete context diagnosis and feature contracts recorded without claiming trained quality, human usability or Cascadeur parity.';s['history'][-1]=result;dest=gp+'01a073fe-c240-70c0-b5cd-fe9653aac60e-sequence-context-v1.json';assert not (ROOT/dest).exists();write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result)+'\n\n'+result['evidence_transport_note']+'\n',encoding='utf-8')
 cp.update(state_path=dest,last_evaluated_state=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=62,remaining_evaluations=38,evidence=ep,decision='iterate',stagnant_rounds=s['stagnant_rounds'],next_controller_monotonic_start=end,active_jobs=[],recorded_at=time.time(),current_turn_classification='Progress: paired context diagnosis completed, serialization mismatch ruled out, explicit observed tangent representation implemented and checked on13analytic contracts and5778training packets. No fit or model promotion.',previous_turn_classification='Progress: generalization diagnosis separated seen and novel proportions and context deficits.',blocked_audit=dict(consecutive_goal_turns=0,condition=None),work_accounting='Parent active-work interval recorded once; no child runtime added.',pending_source_revisions={},pending_document_revisions={})
 cp['latest_live_observation']=dict(context_v1=dict(session_id=24875,terminal=True,exit_code=1,reason='Diagnostic label equality assertion; retained and corrected separately'),context_v2=dict(session_id=78852,terminal=True,exit_code=0),tangent_corpus=dict(session_id=51402,terminal=True,exit_code=0))
 cp['next_safe_actions']=['All jobs terminal. Preserve0.19.1package; no shipped source changed.','Freeze bounded two-seed direct-model experiment adding only explicit tangent conditioning; same corpus, objective, baseline and acceptance. Feature tests do not establish learned quality. Existing weights incompatible.','Use a new compatible model class/training-export path; verify local NumPy parity before fitting; freeze both results before exposed development evaluation. No favorable-seed selection or changes to sealed confirmation.','Preserve full endpoint,100evaluation cap,extended deadline,original quality floors,data/compute limits and deferrals.','Continue full animator intent/contact/physics and end-to-end requirements; independent human usability and equivalent Cascadeur comparison remain pending.']
 cp['publication'].update(committed=False,pushed=False,installed=False,tracked_diff_empty=True,index_empty=True)
 write(base+'checkpoint-sequence-context-v1.json',cp);print(dict(round=62,remaining_evaluations=38,prior_artifacts=len(read(previous)['artifacts']),artifact_count=len(paths),work_seconds=duration,all_jobs_terminal=True,full_goal_complete=False))
if __name__=='__main__':main()
