"""Record observed-only conditioning evidence under the unchanged original goal."""
import copy,time,subprocess
from pathlib import Path
from checkpoint_expanded_goal_v19 import ROOT,read,sha,write,g,evaluate

def main():
    base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/'
    prior=gp+'01a073fe-c240-70c0-b5cd-fe9653aac60e-expanded-trajectory-v19.json';dest=prior.replace('expanded-trajectory-v19','kinematic-trajectory-v20');assert not (ROOT/dest).exists()
    old=read(prior);s=copy.deepcopy(old);cp=read(base+'checkpoint-expanded-trajectory-v19.json');prev_ev=gp+'expanded-trajectory-evidence-v19.json';e=read(prev_ev)
    model=read(res+'kinematic_trajectory_v20/report.json');repro=read(res+'kinematic-trajectory-reproduction-v20.json');assert repro['passed'] and repro['model_artifacts']==6
    for n,h in repro['identical_sha256'].items():assert sha(res+'kinematic_trajectory_v20/'+n)==h==sha(res+'kinematic_trajectory_v20_repeat/'+n)
    reports=[copy.deepcopy(model),read(res+'kinematic_trajectory_v20_repeat/report.json')]
    for report in reports:
        report.pop('runtime');report['model_files']={Path(k).name:v for k,v in report['model_files'].items()}
    assert reports[0]==reports[1]
    oldmodel=read(res+'expanded_trajectory_v19/report.json');assert model['protocol']['gates']==oldmodel['protocol']['gates'];assert model['protocol']['projection']==oldmodel['protocol']['projection'];assert model['protocol']['experiments']==oldmodel['protocol']['experiments'];assert model['training_windows']==7358
    for part in oldmodel['partition_reports']:
        for name in model['protocol']['baselines']:assert model['partition_reports'][part][name]==oldmodel['partition_reports'][part][name]
    feature_checks=read(res+'kinematic-features-complete-checks-v20.json');math_checks=read(res+'kinematic-trajectory-checks-v20.json')
    assert feature_checks['passed'] and feature_checks['reconstruction_uses_only_feature_vector'] and feature_checks['input_features']==548 and len(feature_checks['checks'])==7
    assert math_checks['passed'] and len(math_checks['checks'])==7
    for proof in [feature_checks,math_checks]:
        for n,h in proof['source_sha256'].items():assert sha(tr+n)==h
    plan=read(tr+'temporal_expansion_plan_v19.json');assert all(not (ROOT/tr/'cache'/(c+'.bvh')).exists() for c in plan['planned_splits']['confirmation']);assert not model['confirmation_read']
    moving=read(res+'kinematic-trajectory-host-v20.json');stationary=read(res+'stationary-trajectory-host-v20.json')
    for row in [moving,stationary]:assert row['passed'] and row['complete'] and len(row['rows'])==16 and row['model_sha256']==model['selection']['best_learned_sha256']
    meta=read(base+'package-test-v0.17.2.json');assert meta['ready_for_local_testing'] and sha('releases/b4artists_ml_v0.17.2.zip')==meta['sha256']
    current={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT)) for p in (ROOT/'b4artists_ml').glob('*.py')};assert current==meta['runtime_sha256']==moving['runtime_sha256']==stationary['runtime_sha256']
    changed=[p for p,h in e['artifacts'].items() if sha(p)!=h];assert set(changed)<={base+n+'.md' for n in ['PROJECT','ROADMAP','REQUIREMENTS']},changed
    names=['kinematic_features_v20.py','check_kinematic_features_v20.py','kinematic_trajectory_v20.py','kinematic_readout_v20.py','check_kinematic_trajectory_v20.py','kinematic_trajectory_protocol_v20.json','train_kinematic_trajectory_v20.py','check_kinematic_trajectory_host_v20.py','check_stationary_trajectory_host_v20.py','check_kinematic_reproduction_v20.py','checkpoint_kinematic_goal_v20.py']
    inputs=[tr+n for n in names]+[base+n+'.md' for n in ['KINEMATIC-TRAJECTORY-PLAN-v20','KINEMATIC-TRAJECTORY-v20']];added=[p for p in inputs if p not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract'])
    s['explicit_revisions'].append(dict(reason='Declare a fixed548-input amplitude-relative observed-kinematics experiment, with pre-fit correction preserving34 explicit amplitudes. Corpus, old/new controls, quality thresholds, original endpoint, regression floors and50-evaluation/15-hour resumed limits unchanged.',prior_state=prior,prior_sha256=sha(prior),prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],added_inputs=added,recorded_at=time.time()))
    fp=g.fingerprint(ROOT,s['contract']['inputs']);route_path=gp+'kinematic-conditioning-routing-v20.json';route=read(route_path);route['validation_results']=dict(feature_checks=7,learned_math_checks=7,training_only_coordinate_windows=7358,complete_observed_input_reconstruction=True,reproduction_passed=True,identical_artifacts=6,moving_rig_cases=16,stationary_rig_cases=16,confirmation_untouched=True,development_quality_passed=model['gates']['best_learned']['passed'],full_goal_complete=False);write(route_path,route)
    paths=set(e['artifacts'])|set(inputs)|{prior,prev_ev,route_path}
    for pattern in ['kinematic-*v20*.json','stationary-trajectory-host-v20*.json']:paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res).glob(pattern) if p.is_file())
    for folder in ['kinematic_trajectory_v20','kinematic_trajectory_v20_repeat','kinematic_features_initial_v20']:paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/folder).glob('*') if p.is_file())
    e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={p:sha(p) for p in sorted(paths)},previous_evidence_recheck=dict(path=prev_ev,sha256=sha(prev_ev),changed_artifacts=changed,all_other_prior_artifacts_unchanged=True),learned_host=moving,stationary_host=stationary,temporal_selection=model['selection'],temporal_gates=model['gates'],development_gates=model['development_gates'],reproduction=repro,conditioning_feature_checks=feature_checks,conditioning_math_checks=math_checks,conditioning_prefit_correction=read(res+'kinematic-features-prefit-correction-v20.json'),preserved_milestones=old['passed_progress_milestones'],new_passing_milestones=[])
    e['regression']['note']='Addon0.17.2 source and package bytes unchanged. Prior317-case behavioral coverage,124 offline cases and six package UI events are retained, not a rerun. v20 adds its own32actual-rig and14feature/math checks.'
    e['qualification'].update(full_goal_complete=False,temporal_model_qualification=False,temporal_animator_integration=False,host_shutdown=False,independent_usability='unknown',full_physics_acceptance=False)
    e['limitations']=['Normalization is an observed-only arithmetic encoding, not itself learned animation. Learned gains and failures are recorded against every unchanged procedural control.','Both validation partitions are exposed development data. Six confirmation clips remain absent and no temporal weights are promoted.','Initial514-feature reconstruction depended on external amplitudes; final548-input audit corrects that information loss. Original weaker receipt, source snapshots and correction are retained.','All source data, old/new windows and hyperparameters are fixed. Hidden/readout widths remain64/612;34 extra inputs add2176 weights.','32actual-rig checks do not establish human quality, broad production/quadruped support, responsiveness or Cascadeur parity. The known host shutdown crash persists.','All original learned motion, physics/refinement, rig, distribution, connector and independent usability/comparison requirements remain.']
    args=['git','-c','safe.directory=X:/Scripting Attempts/B4Artists_Tools/B4Artists_Anim_Tools_github'];assert subprocess.check_output(args+['log','-1','--format=%H %an <%ae> %cn <%ce>'],cwd=ROOT,text=True).strip()==cp['publication']['head'];assert not subprocess.check_output(args+['diff','--name-only'],cwd=ROOT,text=True).strip();assert not subprocess.check_output(args+['diff','--cached','--name-only'],cwd=ROOT,text=True).strip()
    ep=gp+'kinematic-trajectory-evidence-v20.json';write(ep,e);obs=read(gp+'expanded-trajectory-observations-v19.json')
    for group in obs.values():
        for proof in group.values():proof.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
    write(gp+'kinematic-trajectory-observations-v20.json',obs)
    end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];event='controller-kinematic-trajectory-v20';assert event not in s['work_events'];g.record_work(s,event,duration);result=evaluate(s,obs,ROOT)
    assert result['round']==33 and result['decision']=='iterate';assert not result['implementation_progress']['new'] and not result['implementation_progress']['lost'];assert all(not c['regression'] for c in result['categories'].values());assert s['history'][:-1]==old['history'];assert cp['max_goalposts']==50 and cp['resumed_run_time_cap_hours']==15
    write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result),encoding='utf-8')
    cp.update(state_path=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=33,remaining_evaluations=17,decision=result['decision'],stagnant_rounds=s['stagnant_rounds'],evidence=ep,active_jobs=[],next_controller_monotonic_start=end,current_turn_classification='Progress: observed-only conditioning corrected/verified, fixed learned experiment reproduced, original controls preserved and32real-rig checks complete. No temporal weights promoted.',work_accounting='Recorded controller-kinematic-trajectory-v20 once from313168.9301766; all conditioning checks, training, reproduction and host handles terminal.',next_safe_actions=['Read original objective and this checkpoint; preserve50 total evaluations and15-hour resumed deadline.','Use the recorded separate development gates to decide further learned work. Keep confirmation sealed unless all gates pass; do not retune v20 against exposed validation.','Prioritize a concrete animator motion-review artifact and measured runtime responsiveness work alongside remaining learned weaknesses, rather than treating model diagnostics as completed animator workflows.','Preserve all original physics/refinement, broader humanoid/quadruped, optional connector, distribution and independent animator/equivalent Cascadeur requirements.'],recorded_at=time.time())
    write(base+'checkpoint-kinematic-trajectory-v20.json',cp);progress=read(base+'kinematic-trajectory-progress-v20.json');progress.update(status='evaluated',active_jobs=[],latest_checkpoint=base+'checkpoint-kinematic-trajectory-v20.json',remaining_evaluations=17,recorded_at=time.time());write(base+'kinematic-trajectory-progress-v20.json',progress)
    print(dict(round=33,remaining=17,decision=result['decision'],stagnant_rounds=s['stagnant_rounds'],work_seconds=duration,full_goal_complete=False))
if __name__=='__main__':main()
