"""Record fixed model rejection and validated private runtime with pending archive check."""
import copy,time,argparse
from checkpoint_expanded_goal_v19 import ROOT,read,write,sha,g
from evaluate_milestone_goal_v2 import evaluate

def main():
 parser=argparse.ArgumentParser();parser.add_argument('--package-session',type=int,required=True);args=parser.parse_args()
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/';cp=read(base+'checkpoint-sequence-training-v1.json');old=read(cp['state_path']);s=copy.deepcopy(old);previous=cp['evidence'];e=read(previous)
 assert cp['round']==59 and s['contract']['max_goalposts']==100 and cp['deadline_unix']==1789053845.
 replacements={'b4artists_ml/'+n:res+'private-production-baseline-v1/'+n for n in ('__init__.py','temporal_generation.py','temporal_preview.py')};changed={n for n,h in e['artifacts'].items() if sha(n)!=h};assert changed==set(replacements),changed
 revisions={}
 for n,b in replacements.items():assert sha(b)==e['artifacts'][n];revisions[n]=dict(prior_version=b,before_sha256=sha(b),after_sha256=sha(n))
 model=read(res+'sequence-development-v1/report.json');assert model['complete'] and model['protected_baselines_match'] and not any(model['family_passes'].values()) and not model['confirmation_read']
 rows=read(res+'private-production-full-v1-regression.json');extra=read(res+'private-production-fallback-v1-regression.json');assert len(rows)==41 and sum(r['tests'] for r in rows)==407 and len(extra)==1 and extra[0]['tests']==1
 runtime={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT)) for p in (ROOT/'b4artists_ml').glob('*.py')};assert all(r['assertions_passed'] and not r['errors'] and not r['failures'] and not r['skipped'] and r['runtime_sha256']==runtime for r in rows+extra)
 benchmark=read(res+'private-production-benchmark-v1/report.json');assert benchmark['complete'] and benchmark['runtime_sha256']==runtime and benchmark['ratio']<=.9
 meta=read(base+'package-test-v0.19.1.json');assert meta['runtime_sha256']==runtime and sha('releases/b4artists_ml_v0.19.1.zip')==meta['sha256']
 assert read(res+'sequence-coverage-audit-v1.json')['complete'] and read(res+'sequence-training-diagnosis-v1/report.json')['complete']
 names=['private_production_plan_v1.json','private_production_regression_plan_v1.json','benchmark_private_production_v1.py','build_private_runtime_package_v1.py','check_private_runtime_package_v1.py','audit_sequence_coverage_v1.py','diagnose_sequence_training_v1.py','checkpoint_private_production_v1.py']
 inputs=[tr+n for n in names]+['b4artists_ml/temporal_private.py','tests/test_b4artists_ml_temporal_private_v1.py','tests/test_b4artists_ml_private_fallback_v1.py',base+'SEQUENCE-DEVELOPMENT-v1.md'];added=[n for n in inputs if n not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract']);a=copy.deepcopy(s['contract']);b=copy.deepcopy(old['contract']);a.pop('inputs');b.pop('inputs');assert a==b
 s['explicit_revisions'].append(dict(reason='Fixed sequence models failed original gates; private preview runtime preserves solver/guard mathematics and passes408native checks plus controlled performance gate. Same endpoint, limits, floors and history; exact archive verification remains active.',prior_state=cp['state_path'],prior_sha256=sha(cp['state_path']),added_inputs=added,source_revisions=revisions,prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],recorded_at=time.time()))
 paths=set(e['artifacts'])|set(inputs)|set(replacements.values())|{cp['state_path'],previous,gp+'private-production-routing-v1.json',res+'private-production-source-audit-v1.json',res+'sequence-coverage-audit-v1.json',base+'package-test-v0.19.1.json','releases/b4artists_ml_v0.19.1.zip'}
 for folder in ('sequence-development-v1','sequence-training-diagnosis-v1','private-production-baseline-v1','private-production-benchmark-v1'):
  paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/folder).rglob('*') if p.is_file())
 for prefix in ('private-production-focused-v1','private-production-full-v1','private-production-fallback-v1'):
  paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res).glob(prefix+'*.json'))
  paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/tr/'cache').glob(prefix+'*.log'))
 assert all(not (ROOT/tr/'cache'/(n+'.bvh')).exists() for n in read(tr+'temporal_expansion_plan_v19.json')['planned_splits']['confirmation'])
 fp=g.fingerprint(ROOT,s['contract']['inputs']);e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={n:sha(n) for n in sorted(paths)},previous_evidence_recheck=dict(path=previous,sha256=sha(previous),all_unrevised_artifacts_unchanged=True,source_revisions=revisions),private_production=dict(native_cases=408,benchmark=res+'private-production-benchmark-v1/report.json',median_ratio=benchmark['ratio'],archive_version='0.19.1',archive_verification_pending=True,sequence_families_passed=model['family_passes'],full_quality_qualified=False))
 e['qualification'].update(temporal_model_qualification=False,independent_usability='unknown',full_goal_complete=False);ep=gp+'private-production-evidence-v1.json';write(ep,e);obs=read(gp+'sequence-training-observations-v1.json')
 for group in obs.values():
  for row in group.values():row.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 op=gp+'private-production-observations-v1.json';write(op,obs);end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];g.record_work(s,'controller-private-production-v1',duration);result=evaluate(s,obs,ROOT)
 assert result['round']==60 and result['decision']=='iterate' and s['history'][:-1]==old['history'] and s['floors']==old['floors'];result['evidence_transport_note']='Authenticated assessment and independent review unavailable. Exact model failures, native correctness and serial performance evidence recorded; full motion quality/human usability/Cascadeur comparison remain unqualified.';s['history'][-1]=result;dest=gp+'01a073fe-c240-70c0-b5cd-fe9653aac60e-private-production-v1.json';assert not (ROOT/dest).exists();write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result)+'\n\n'+result['evidence_transport_note']+'\n',encoding='utf-8')
 cp.update(state_path=dest,last_evaluated_state=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=60,remaining_evaluations=40,evidence=ep,decision='iterate',stagnant_rounds=s['stagnant_rounds'],next_controller_monotonic_start=end,active_jobs=[dict(kind='unified_exec',session_id=args.package_session,task='Exact0.19.1offline archive verification; thirteen existing workflows',report=res+'private-runtime-package-v1.json')],recorded_at=time.time(),current_turn_classification='Progress:all four sequence fits rejected by original gates; training/coverage diagnoses; private preview runtime408native checks and controlled speedup; exact archive checking.',blocked_audit=dict(consecutive_goal_turns=0,condition=None),work_accounting='Parent active-work interval recorded once; no child runtime added.',pending_source_revisions={},pending_document_revisions={})
 cp['artifact']=dict(path='releases/b4artists_ml_v0.19.1.zip',sha256=meta['sha256'],files=meta['files'],bytes=meta['bytes'],matches_current_source=True,experimental=True,ready_for_local_testing=False,note='408native checks and controlled private-rig speedup; exact archive offline workflow check still active. No qualified temporal model.')
 cp['latest_live_observation']=dict(development=dict(session_id=37528,terminal=True,exit_code=0,both_model_families_failed=True),native=dict(session_id=31188,terminal=True,exit_code=0,cases=407),fallback=dict(terminal=True,exit_code=0,cases=1),training_diagnosis=dict(session_id=1584,terminal=True,exit_code=0),benchmark=dict(session_id=39854,terminal=True,exit_code=0),package=dict(session_id=args.package_session,live_verified=True))
 cp['next_safe_actions']=['Revalidate the same exact-package job; finish13offline workflows before marking the0.19.1archive ready. Do not restart a live job on observation timeout.','Finalize user guide, requirements, roadmap and measured-performance document from preserved document baselines; keep goal incomplete.','Preserve failed sequence weights and both-seed original gates; no nearby fitting variants. Training diagnosis shows learned training examples, but development remains worse.','Investigate generalization/request distribution/projection and explicit contact/intent representation under a new bounded hypothesis before further fitting; sealed confirmation remains sealed.','Keep100ceiling,extendeddeadline,full endpoint,existing deferrals,identity and publication approvals.']
 write(base+'checkpoint-private-production-v1.json',cp);print(dict(round=60,remaining_evaluations=40,prior_artifacts=len(read(previous)['artifacts']),source_revisions=len(revisions),artifact_count=len(paths),work_seconds=duration,active_package_session=args.package_session,full_goal_complete=False))
if __name__=='__main__':main()
