"""Record finalization evidence without narrowing the original active goal."""
import copy,time,subprocess,zipfile,hashlib
from pathlib import Path
from checkpoint_expanded_goal_v19 import ROOT,read,sha,write,g,evaluate

def main():
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/'
 prior=gp+'01a073fe-c240-70c0-b5cd-fe9653aac60e-cooperative-preparation-v1.json';dest=prior.replace('cooperative-preparation-v1','cooperative-finalization-v1');assert not (ROOT/dest).exists()
 old=read(prior);s=copy.deepcopy(old);cp=read(base+'checkpoint-cooperative-preparation-v1.json');prev_ev=gp+'cooperative-preparation-evidence-v1.json';e=read(prev_ev)
 meta=read(base+'package-test-v0.17.4.json');assert meta['ready_for_local_testing'] and meta['regression']['unique_cases']==330 and meta['regression']['all_refreshed'] and meta['regression']['suites']==31;assert meta['packaged_host_smoke']=='passed' and meta['packaged_offline_cases']==4
 current={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT)) for p in (ROOT/'b4artists_ml').glob('*.py')};assert current==meta['runtime_sha256'];assert sha('releases/b4artists_ml_v0.17.4.zip')==meta['sha256']
 with zipfile.ZipFile(ROOT/'releases/b4artists_ml_v0.17.4.zip') as z:assert all(z.read(n)==(ROOT/n).read_bytes() for n in z.namelist())
 smoke=read(res+'finalization-package-v1.json');assert smoke['passed'] and smoke['runtime_sha256']==current and smoke['package_sha256']==meta['sha256'] and smoke['offline_guard_self_test'] and not smoke['denied_runtime_calls']
 bench=read(res+'finalization-benchmark-v2.json');assert bench['passed'] and bench['complete'];assert all(c['exact_pose_signature_metrics_parity'] and c['source_preserved'] for c in bench['comparisons'])
 first=read(res+'finalization-benchmark-v1.json');assert not first['passed'] and first['complete']
 fault=read(res+'finalization-fault-comparison-v1.json');assert fault['passed'] and fault['complete'];assert all(not x['verified_preview_restored'] for x in fault['rows'][0]['report']['rows']);assert all(x['verified_preview_restored'] for x in fault['rows'][1]['report']['rows'])
 plan=read(tr+'temporal_expansion_plan_v19.json');assert all(not (ROOT/tr/'cache'/(c+'.bvh')).exists() for c in plan['planned_splits']['confirmation'])
 changed=[p for p,h in e['artifacts'].items() if sha(p)!=h];versions={}
 with zipfile.ZipFile(ROOT/'releases/b4artists_ml_v0.17.3.zip') as z:
  for p in changed:
   if p in z.namelist():
    assert hashlib.sha256(z.read(p)).hexdigest()==e['artifacts'][p];versions[p]=dict(archive='releases/b4artists_ml_v0.17.3.zip',entry=p,sha256=e['artifacts'][p])
   else:
    snapshot=res+'finalization-document-baseline-v1/'+Path(p).name
    assert p in {base+n+'.md' for n in ['PROJECT','ROADMAP','REQUIREMENTS','USER_GUIDE']} and sha(snapshot)==e['artifacts'][p];versions[p]=dict(path=snapshot,sha256=sha(snapshot))
 names=['profile_finalization_v1.py','profile_finalization_v2.py','profile_hot_ticks_v1.py','cooperative_finalization_plan_v1.json','cooperative_finalization_amendment_v1.json','check_finalization_fault_v1.py','check_bulk_rest_read_v1.py','benchmark_finalization_v1.py','benchmark_finalization_v2.py','finalization_regression_plan_v1.json','build_finalization_package_v1.py','check_finalization_package_v1.py','finalize_finalization_package_v1.py','checkpoint_finalization_goal_v1.py']
 inputs=[tr+n for n in names]+['tests/test_b4artists_ml_finalization.py','tests/test_b4artists_ml_bulk_structure.py',base+'FINALIZATION-PERFORMANCE-v1.md'];added=[p for p in inputs if p not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract'])
 s['explicit_revisions'].append(dict(reason='Add bounded finalization/cancellation, released/current malformed-record recovery proof, and uncached structural reads with exact saved-format compatibility. Original endpoint, timing gates, protected scores, passed milestones and 50-evaluation/15-hour resumed limits remain unchanged.',prior_state=prior,prior_sha256=sha(prior),prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],added_inputs=added,recorded_at=time.time()))
 fp=g.fingerprint(ROOT,s['contract']['inputs']);route_path=gp+'cooperative-finalization-routing-v1.json';route=read(route_path);route['validation_results']=dict(fresh_regression_cases=330,exact_package_offline_cases=4,final_counterbalanced_comparison_passed=True,first_comparison_passed=False,released_rollback_defect_reproduced_on_two_rigs=True,current_rollback_fixed=True,serialized_structure_exact=True,full_goal_complete=False);write(route_path,route)
 paths=set(e['artifacts'])|set(inputs)|{res+'temporal-failure-attribution-v20.json',prior,prev_ev,route_path,base+'package-test-v0.17.4.json','releases/b4artists_ml_v0.17.4.zip'}
 for pattern in ['finalization*.json','hot-tick-profile*.json','bulk-rest*.json','bulk-structure*.json','cooperative-finalization-final-v1*.json']:paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res).glob(pattern) if p.is_file())
 for folder in ['finalization-initial-v1','finalization-document-baseline-v1']:paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/folder).glob('*') if p.is_file())
 e['packaged_ui']=dict(current_package_verified=False,source_ui_unchanged_from='0.17.2',note='Historical actual-window evidence retained. Current package has headless offline lifecycle coverage; no UI event or visual approval claimed.')
 e['offline']=smoke
 e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={p:sha(p) for p in sorted(paths)},previous_evidence_recheck=dict(path=prev_ev,sha256=sha(prev_ev),changed_artifacts=changed,preserved_prior_versions=versions,all_other_prior_artifacts_unchanged=True),package=dict(path='releases/b4artists_ml_v0.17.4.zip',sha256=meta['sha256'],files=meta['files'],bytes=meta['bytes'],matches_current_source=True,experimental=True),regression=dict(passed=True,unique_cases=330,suites=31,refreshed_cases=330,reused_cases=0,all_current_behavior_runs=True,version_only_metadata_change_after_checks=meta['version_only_change_after_checks'],current_coverage_verified=True,note='All prior suites plus six finalization and three structural cases refreshed. Four additional exact-package offline cases.'),finalization_comparison=bench['comparisons'],finalization_first_comparison=first['comparisons'],finalization_fault_comparison=fault,bulk_structure_prototype=read(res+'bulk-rest-read-v1.json'),preserved_milestones=old['passed_progress_milestones'],new_passing_milestones=[])
 e['qualification'].update(full_goal_complete=False,temporal_model_qualification=False,temporal_animator_integration=False,host_shutdown=False,independent_usability='unknown',full_physics_acceptance=False,full_responsiveness=False,current_package_ui='unverified')
 e['limitations']=['The fixed scoped timing gates pass, but worst ticks still exceed 50 ms and complete solves take seconds. Full responsiveness remains failed.','The first timing candidate missed its maximum-tick target and is retained. Structural-read optimization was declared and tested before a new comparison; no target was weakened.','The released/current fault probe predates the bulk-read optimization; the final 330-case run refreshes completion rollback and exact structural-format guards on the final behavior.','Current-package offline checks establish local execution and recovery, not UI queue latency or independent human usability. Historical UI proof stays attached to its original release.','Browser URL policy still blocks local HTML interaction verification. No workaround, alternate surface or invented reviewer ratings were used.','Temporal models remain unqualified and unbundled; six fresh confirmation clips remain absent. All original learned motion, physics/refinement, broad humanoid/quadruped support, optional connector, distribution and equivalent Cascadeur comparison requirements remain.','Known host shutdown crashes are recorded separately from passed assertions.']
 args=['git','-c','safe.directory=X:/Scripting Attempts/B4Artists_Tools/B4Artists_Anim_Tools_github'];assert subprocess.check_output(args+['log','-1','--format=%H %an <%ae> %cn <%ce>'],cwd=ROOT,text=True).strip()==cp['publication']['head'];assert not subprocess.check_output(args+['diff','--name-only'],cwd=ROOT,text=True).strip();assert not subprocess.check_output(args+['diff','--cached','--name-only'],cwd=ROOT,text=True).strip()
 ep=gp+'cooperative-finalization-evidence-v1.json';write(ep,e);obs=read(gp+'cooperative-preparation-observations-v1.json')
 for group in obs.values():
  for proof in group.values():proof.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 write(gp+'cooperative-finalization-observations-v1.json',obs)
 end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];event='controller-cooperative-finalization-v1';assert event not in s['work_events'];g.record_work(s,event,duration);result=evaluate(s,obs,ROOT)
 assert result['round']==35 and result['decision']=='iterate';assert not result['implementation_progress']['new'] and not result['implementation_progress']['lost'];assert all(not c['regression'] for c in result['categories'].values());assert s['history'][:-1]==old['history'];assert cp['max_goalposts']==50 and cp['resumed_run_time_cap_hours']==15
 write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result),encoding='utf-8')
 cp.update(state_path=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=35,remaining_evaluations=15,decision=result['decision'],stagnant_rounds=s['stagnant_rounds'],evidence=ep,artifact=e['package'],active_jobs=[],next_controller_monotonic_start=end,current_turn_classification='Progress: measured finalization reduction, reproduced/fixed released completion rollback defect, exact structural-read optimization, 330 fresh cases and four offline package cases. Full original goal remains incomplete.',work_accounting='Recorded controller-cooperative-finalization-v1 once from318890.4630454; profile, test, comparison and package handles terminal.',next_safe_actions=['Read the original objective and checkpoint; preserve 50 total evaluations and the unchanged 15-hour resumed deadline.','Use temporal-failure-attribution-v20.json to plan the next learned experiment: 24 of 25 failed cohorts also expose shape-reference weakness, but harmful residuals amplify the two worst cases by over 2x. Address both, using training-only selection and unchanged frozen gates; keep six confirmation clips sealed.','Full posing responsiveness still requires lower complete-solve cost. Any warm-start or analytic initialization must demonstrate quality and recovery, not merely fewer iterations.','Continue original physics/refinement, broad humanoid/quadruped, optional connector and distribution requirements.','Independent animator review and equivalent Cascadeur comparisons remain unknown; do not fabricate them or bypass the browser URL policy.'],recorded_at=time.time())
 write(base+'checkpoint-cooperative-finalization-v1.json',cp);progress=read(base+'finalization-progress-v1.json');progress.update(status='evaluated',active_jobs=[],latest_checkpoint=base+'checkpoint-cooperative-finalization-v1.json',remaining_evaluations=15,recorded_at=time.time());write(base+'finalization-progress-v1.json',progress)
 print(dict(round=35,remaining=15,decision=result['decision'],stagnant_rounds=s['stagnant_rounds'],work_seconds=duration,full_goal_complete=False))
if __name__=='__main__':main()
