"""Preserve research cache evidence and the original finite run boundary."""
import copy,time,subprocess,zipfile
from pathlib import Path
from checkpoint_expanded_goal_v19 import ROOT,read,sha,write,g,evaluate

def main():
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/';prefix='01a073fe-c240-70c0-b5cd-fe9653aac60e-';prior=gp+prefix+'pruning-experiments-v1.json';dest=gp+prefix+'record-cache-v1.json';assert not (ROOT/dest).exists();old=read(prior);s=copy.deepcopy(old);cp=read(base+'checkpoint-pruning-experiments-v1.json');prev_ev=gp+'pruning-experiments-evidence-v1.json';e=read(prev_ev)
 measured=read(res+'record-copy-v1.json');checks=read(res+'record-cache-check-v1.json');bench=read(res+'record-cache-benchmark-v1.json');assert measured['complete'] and measured['passed'] and len(measured['rows'])==5;assert checks['complete'] and checks['passed'] and sum(r['tests'] for r in checks['rows'])==15;assert bench['complete'] and bench['passed'] and all(r['exact_pose_signature_metrics_parity'] and r['source_preserved'] for r in bench['comparisons']);assert bench['prototype_sha256']==sha(tr+'record_cache_prototype_v1.py')
 for row in checks['rows']:assert row['cache_invariants_passed'] and row['prototype_sha256']==bench['prototype_sha256']
 meta=read(base+'package-test-v0.17.4.json');current={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT)) for p in (ROOT/'b4artists_ml').glob('*.py')};assert current==meta['runtime_sha256']==measured['runtime_sha256'];assert all(r['runtime_sha256']==current for r in checks['rows']+bench['rows']);assert sha('releases/b4artists_ml_v0.17.4.zip')==meta['sha256']
 with zipfile.ZipFile(ROOT/'releases/b4artists_ml_v0.17.4.zip') as z:assert all(z.read(n)==(ROOT/n).read_bytes() for n in z.namelist())
 changed=[p for p,h in e['artifacts'].items() if sha(p)!=h];assert set(changed)=={base+n+'.md' for n in ['PROJECT','ROADMAP','REQUIREMENTS']},changed;versions={}
 for p in changed:
  snapshot=res+'record-cache-document-baseline-v1/'+Path(p).name;assert sha(snapshot)==e['artifacts'][p];versions[p]=dict(path=snapshot,sha256=sha(snapshot))
 names=['record_copy_plan_v1.json','profile_record_copy_v1.py','record_cache_plan_v1.json','record_cache_prototype_v1.py','check_record_cache_v1.py','benchmark_record_cache_v1.py','checkpoint_record_cache_goal_v1.py'];inputs=[tr+n for n in names]+[base+'RECORD-CACHE-PLAN-v1.md',base+'RECORD-CACHE-v1.md'];added=[p for p in inputs if p not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract']);s['explicit_revisions'].append(dict(reason='Add actual-record reconstruction measurement and bounded research-only cache with15existing guards and exact five-profile comparison. No production/runtime/package promotion. Original full endpoint, floors/milestones,50total evaluations and fixed15-hour deadline unchanged.',prior_state=prior,prior_sha256=sha(prior),prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],added_inputs=added,recorded_at=time.time()));fp=g.fingerprint(ROOT,s['contract']['inputs']);paths=set(e['artifacts'])|set(inputs)|{prior,prev_ev,gp+'record-copy-routing-v1.json',gp+'record-cache-routing-v1.json'}
 for pattern in ['record-copy-v1*.json','record-cache-check-v1*.json','record-cache-benchmark-v1*.json']:paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res).glob(pattern) if p.is_file())
 for pattern in ['record-copy-v1*.log','record-cache-check-v1*.log','record-cache-benchmark-v1*.log']:paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/tr/'cache').glob(pattern) if p.is_file())
 paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/'record-cache-document-baseline-v1').glob('*'))
 plan=read(tr+'temporal_expansion_plan_v19.json');assert all(not (ROOT/tr/'cache'/(c+'.bvh')).exists() for c in plan['planned_splits']['confirmation'])
 e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={p:sha(p) for p in sorted(paths)},previous_evidence_recheck=dict(path=prev_ev,sha256=sha(prev_ev),changed_artifacts=changed,preserved_prior_versions=versions,all_other_prior_artifacts_unchanged=True),record_reconstruction_measurement=measured,record_cache_prototype_checks=checks,record_cache_comparison=bench['comparisons'],production_cache_integrated=False,preserved_milestones=old['passed_progress_milestones'],new_passing_milestones=[])
 e['regression'].update(rerun_this_iteration=False,retained_from=prev_ev,note='Production0.17.4unchanged. Existing330-case coverage, one proxy-isolation check and four offline checks retained.15existing guards executed under a research-only cache are not a full production regression.')
 e['qualification'].update(full_goal_complete=False,temporal_model_qualification=False,temporal_animator_integration=False,host_shutdown=False,independent_usability='unknown',full_physics_acceptance=False,full_responsiveness=False)
 e['limitations']=['Cache exists only in research hosts; production lifecycle/cleanup, malformed-input coverage, memory profiling, full regression and package tests remain pending.','Scoped timing gates pass with exact five-profile results, but default Rigify worst ticks still exceed50ms and UI/human usability remain unverified.','Known host shutdown crash persists after assertions. Runtime and ZIP0.17.4remain byte-identical.','All original learned workflow, physics/refinement, rig/quadruped, connector, distribution and equivalent Cascadeur requirements remain incomplete; confirmation remains sealed.']
 args=['git','-c','safe.directory=X:/Scripting Attempts/B4Artists_Tools/B4Artists_Anim_Tools_github'];assert subprocess.check_output(args+['log','-1','--format=%H %an <%ae> %cn <%ce>'],cwd=ROOT,text=True).strip()==cp['publication']['head'];assert not subprocess.check_output(args+['diff','--name-only'],cwd=ROOT,text=True).strip();assert not subprocess.check_output(args+['diff','--cached','--name-only'],cwd=ROOT,text=True).strip()
 ep=gp+'record-cache-evidence-v1.json';write(ep,e);obs=read(gp+'pruning-experiments-observations-v1.json')
 for group in obs.values():
  for proof in group.values():proof.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 write(gp+'record-cache-observations-v1.json',obs);end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];event='controller-record-cache-v1';assert event not in s['work_events'];g.record_work(s,event,duration);result=evaluate(s,obs,ROOT)
 assert result['round']==42 and result['decision']=='iterate';assert not result['implementation_progress']['new'] and not result['implementation_progress']['lost'];assert all(not c['regression'] for c in result['categories'].values());assert s['history'][:-1]==old['history'];assert cp['max_goalposts']==50 and cp['resumed_run_time_cap_hours']==15 and cp['deadline_unix']==1788902277.2365775
 write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result),encoding='utf-8')
 cp.update(state_path=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=42,remaining_evaluations=8,decision=result['decision'],stagnant_rounds=s['stagnant_rounds'],evidence=ep,active_jobs=[],next_controller_monotonic_start=end,current_turn_classification='Progress: actual-record measurement motivated bounded research cache;15existing guards and exact five-profile timing pass. Default Rigify idle p95improves32.6%, total work13.5%. Production remains unchanged; full original goal incomplete.',work_accounting='Recorded controller-record-cache-v1 once from331953.5751693; measurement86347,guards23661 and comparison40790terminal.',next_safe_actions=['Check the current clock before any further development. The unchanged15-hour deadline is21:17:57UTC; checkpoint when reached.50total evaluations remain the ceiling, with8unused evaluations.', 'If time is extended, route production integration of bounded record copying, explicit cache cleanup/lifetime and malformed-input checks; run full regression, memory/resource and exact-package checks before promotion.', 'Keep all models/confirmation frozen; full learned workflow, physics/refinement, rig/quadruped, optional connector, distribution, responsiveness, independent animator and Cascadeur requirements remain.', 'Do not mark the original goal complete at the time cap. Preserve this same goal, contract, evidence and progress; require a new time allowance before new development after the cap.'],recorded_at=time.time());write(base+'checkpoint-record-cache-v1.json',cp)
 progress=read(base+'record-cache-progress-v1.json');progress.update(status='evaluated',latest_checkpoint=base+'checkpoint-record-cache-v1.json',round=42,remaining_evaluations=8,active_jobs=[],recorded_at=time.time());write(base+'record-cache-progress-v1.json',progress);print(dict(round=42,remaining=8,decision=result['decision'],work_seconds=duration,next_controller_monotonic_start=end,deadline_reached=time.time()>=cp['deadline_unix'],full_goal_complete=False))
if __name__=='__main__':main()
