"""Preserve the original goal while recording motion review and preparation work."""
import copy,time,subprocess,zipfile,hashlib
from pathlib import Path
from checkpoint_expanded_goal_v19 import ROOT,read,sha,write,g,evaluate

def main():
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/'
 prior=gp+'01a073fe-c240-70c0-b5cd-fe9653aac60e-kinematic-trajectory-v20.json';dest=prior.replace('kinematic-trajectory-v20','cooperative-preparation-v1');assert not (ROOT/dest).exists()
 old=read(prior);s=copy.deepcopy(old);cp=read(base+'checkpoint-kinematic-trajectory-v20.json');prev_ev=gp+'kinematic-trajectory-evidence-v20.json';e=read(prev_ev)
 meta=read(base+'package-test-v0.17.3.json');assert meta['ready_for_local_testing'] and meta['regression']['unique_cases']==321 and meta['regression']['all_refreshed'];assert meta['packaged_host_smoke']=='passed' and meta['packaged_offline_cases']==4
 current={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT)) for p in (ROOT/'b4artists_ml').glob('*.py')};assert current==meta['runtime_sha256'];assert sha('releases/b4artists_ml_v0.17.3.zip')==meta['sha256']
 with zipfile.ZipFile(ROOT/'releases/b4artists_ml_v0.17.3.zip') as z:assert all(z.read(n)==(ROOT/n).read_bytes() for n in z.namelist())
 smoke=read(res+'cooperative-package-v1.json');assert smoke['passed'] and smoke['runtime_sha256']==current and smoke['package_sha256']==meta['sha256'] and smoke['offline_guard_self_test'] and not smoke['denied_runtime_calls']
 bench=read(res+'preparation-benchmark-v2.json');assert bench['passed'] and bench['complete'];assert all(c['exact_pose_signature_metrics_parity'] and c['source_preserved'] for c in bench['comparisons'])
 review=read(res+'motion-review-build-v1.json');static=read(res+'motion-review-static-verification-v1.json');assert review['passed'] and static['passed'] and static['cases']==96 and not static['browser_interaction_verified'] and static['ratings_entered_by_agent']==0
 assert sha(base+'motion-review-v1/index.html')==static['html_sha256'];assert sha(base+'motion-review-v1/motion-data.json')==static['data_sha256']
 plan=read(tr+'temporal_expansion_plan_v19.json');assert all(not (ROOT/tr/'cache'/(c+'.bvh')).exists() for c in plan['planned_splits']['confirmation'])
 changed=[p for p,h in e['artifacts'].items() if sha(p)!=h];versions={}
 with zipfile.ZipFile(ROOT/'releases/b4artists_ml_v0.17.2.zip') as z:
  for p in changed:
   if p in z.namelist():
    assert hashlib.sha256(z.read(p)).hexdigest()==e['artifacts'][p];versions[p]=dict(archive='releases/b4artists_ml_v0.17.2.zip',entry=p,sha256=e['artifacts'][p])
   else:
    snapshot=res+'cooperative-preparation-document-baseline-v1/'+Path(p).name
    assert p in {base+n+'.md' for n in ['PROJECT','ROADMAP','REQUIREMENTS','USER_GUIDE']} and sha(snapshot)==e['artifacts'][p];versions[p]=dict(path=snapshot,sha256=sha(snapshot))
 names=['motion_review_plan_v1.json','build_motion_review_v1.py','motion_review_template_v1.html','profile_active_preview_v1.py','cooperative_preparation_plan_v1.json','run_cooperative_checks_v1.py','benchmark_preparation_v1.py','benchmark_preparation_v2.py','cooperative_regression_plan_v1.json','build_cooperative_package_v1.py','check_cooperative_package_v1.py','finalize_cooperative_package_v1.py','checkpoint_cooperative_goal_v1.py']
 inputs=[tr+n for n in names]+['tests/test_b4artists_ml_cooperative_proxy.py',base+'MOTION-REVIEW-v1.md',base+'COOPERATIVE-PREPARATION-v1.md',base+'motion-review-v1/index.html',base+'motion-review-v1/motion-data.json']
 added=[p for p in inputs if p not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract'])
 s['explicit_revisions'].append(dict(reason='Add a fixed 96-cohort diagnostic motion viewer and cancellable preparation implementation with counterbalanced timing and complete regression. Original endpoint, quality thresholds, passed milestones, protected scores and 50-evaluation/15-hour resumed limits remain unchanged.',prior_state=prior,prior_sha256=sha(prior),prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],added_inputs=added,recorded_at=time.time()))
 fp=g.fingerprint(ROOT,s['contract']['inputs']);route_path=gp+'cooperative-preparation-routing-v1.json';route=read(route_path);route['validation_results']=dict(fresh_regression_cases=321,exact_package_offline_cases=4,counterbalanced_comparison_passed=True,source_preserved=True,viewer_cases=96,static_viewer_verification=True,viewer_browser_interaction=False,full_goal_complete=False);write(route_path,route)
 paths=set(e['artifacts'])|set(inputs)|{prior,prev_ev,route_path,gp+'review-responsiveness-routing-v1.json',base+'package-test-v0.17.3.json','releases/b4artists_ml_v0.17.3.zip'}
 for pattern in ['motion-review*.json','motion-review*.js','active-preview-profile-v1*.json','cooperative*.json','preparation-benchmark-v*.json']:paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res).glob(pattern) if p.is_file())
 for folder in ['cooperative-preparation-candidate-v1','cooperative-preparation-document-baseline-v1']:paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/folder).glob('*') if p.is_file())
 paths.add(res+'cooperative-proxy-test-initial-v1.py')
 e['historical_packaged_ui']=copy.deepcopy(e['packaged_ui']);e['packaged_ui']=dict(current_package_verified=False,source_ui_unchanged_from='0.17.2',note='Previous actual-window evidence retained as historical evidence. New package has headless lifecycle coverage; no current UI event or visual claim.')
 e['historical_offline']=copy.deepcopy(e['offline']);e['offline']=smoke
 e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={p:sha(p) for p in sorted(paths)},previous_evidence_recheck=dict(path=prev_ev,sha256=sha(prev_ev),changed_artifacts=changed,preserved_prior_versions=versions,all_other_prior_artifacts_unchanged=True),package=dict(path='releases/b4artists_ml_v0.17.3.zip',sha256=meta['sha256'],files=meta['files'],bytes=meta['bytes'],matches_current_source=True,experimental=True),regression=dict(passed=True,unique_cases=321,suites=29,refreshed_cases=321,reused_cases=0,all_current_behavior_runs=True,version_only_metadata_change_after_checks=meta['version_only_change_after_checks'],current_coverage_verified=True,note='All prior suites refreshed, with preparation-aware proxy lifecycle tests and four new cases; four additional exact-package offline cases.'),preparation_comparison=bench['comparisons'],motion_review=review,motion_review_static=static,preserved_milestones=old['passed_progress_milestones'],new_passing_milestones=[])
 e['qualification'].update(full_goal_complete=False,temporal_model_qualification=False,temporal_animator_integration=False,host_shutdown=False,independent_usability='unknown',full_physics_acceptance=False,full_responsiveness=False,current_package_ui='unverified')
 e['limitations']=['The staged preparation reduces first-tick pauses but adds validation overhead. Default Rigify worst ticks still exceed 50 ms; full responsiveness remains failed.','Complete behavior regression and exact-package headless checks do not establish UI event latency or independent human usability. Prior UI evidence is preserved under its original package.','Browser policy rejected local HTML navigation. Static data and syntax verification only; no alternate browser surface or indirect rendering attempted, and no ratings supplied.','Temporal v19/v20 research and actual-rig evidence remain historical under their original source. New temporal projection regression passes, but no temporal model is qualified or shipped.','The six fresh confirmation clips remain absent. Full physics/refinement, broad humanoid/quadruped support, optional connector, distribution, human quality and equivalent Cascadeur comparison requirements remain.','The existing host shutdown crash persists and is recorded separately from passed assertions.']
 args=['git','-c','safe.directory=X:/Scripting Attempts/B4Artists_Tools/B4Artists_Anim_Tools_github'];assert subprocess.check_output(args+['log','-1','--format=%H %an <%ae> %cn <%ce>'],cwd=ROOT,text=True).strip()==cp['publication']['head'];assert not subprocess.check_output(args+['diff','--name-only'],cwd=ROOT,text=True).strip();assert not subprocess.check_output(args+['diff','--cached','--name-only'],cwd=ROOT,text=True).strip()
 ep=gp+'cooperative-preparation-evidence-v1.json';write(ep,e);obs=read(gp+'kinematic-trajectory-observations-v20.json')
 for group in obs.values():
  for proof in group.values():proof.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 write(gp+'cooperative-preparation-observations-v1.json',obs)
 end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];event='controller-cooperative-preparation-v1';assert event not in s['work_events'];g.record_work(s,event,duration);result=evaluate(s,obs,ROOT)
 assert result['round']==34 and result['decision']=='iterate';assert not result['implementation_progress']['new'] and not result['implementation_progress']['lost'];assert all(not c['regression'] for c in result['categories'].values());assert s['history'][:-1]==old['history'];assert cp['max_goalposts']==50 and cp['resumed_run_time_cap_hours']==15
 write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result),encoding='utf-8')
 cp.update(state_path=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=34,remaining_evaluations=16,decision=result['decision'],stagnant_rounds=s['stagnant_rounds'],evidence=ep,artifact=e['package'],active_jobs=[],next_controller_monotonic_start=end,current_turn_classification='Progress: fixed diagnostic motion viewer, measured cancellable Rigify preparation, source-invalidation recovery fix, 321 fresh regression cases and four exact-package offline cases. Full quality gates remain unchanged.',work_accounting='Recorded controller-cooperative-preparation-v1 once from314908.7796605; review/profile/test/benchmark/package handles terminal.',next_safe_actions=['Read the original objective and this checkpoint; preserve the 50 total evaluations and 15-hour resumed deadline.','Prioritize remaining per-tick validation/finalization cost or the weakest learned-motion cohorts using a prospective experiment; preserve all passing recovery and accuracy checks.','Keep six confirmation clips sealed unless all frozen development gates pass. No temporal candidate is qualified or bundled.','Independent animator review and equivalent Cascadeur comparison remain unknown. Do not bypass the local-browser URL policy or fabricate review ratings.','Continue the original physics/refinement, broader rig and quadruped, optional connector and distribution requirements.'],recorded_at=time.time())
 write(base+'checkpoint-cooperative-preparation-v1.json',cp);print(dict(round=34,remaining=16,decision=result['decision'],stagnant_rounds=s['stagnant_rounds'],work_seconds=duration,full_goal_complete=False))
if __name__=='__main__':main()
