"""Record controlled diagnostics without changing or narrowing the original goal."""
import copy,time,subprocess,zipfile
from pathlib import Path
from checkpoint_expanded_goal_v19 import ROOT,read,sha,write,g,evaluate

def main():
 base='docs/b4artists_ml/';gp=base+'goalposts/';tr='training/b4artists_ml/';res=tr+'results/';prefix='01a073fe-c240-70c0-b5cd-fe9653aac60e-'
 prior=gp+prefix+'joint-mixture-v24.json';dest=gp+prefix+'component-diagnosis-v25.json';assert not (ROOT/dest).exists();old=read(prior);s=copy.deepcopy(old);cp=read(base+'checkpoint-joint-mixture-v24.json');prev_ev=gp+'joint-mixture-evidence-v24.json';e=read(prev_ev)
 cross=read(res+'crossed-components-v25.json');profile=read(res+'current-tick-profile-v25.json');process=read(res+'current-tick-profile-v25-process.json');assert cross['complete'] and cross['raw_donor_invariance_passed'] and not cross['confirmation_accessed'];assert profile['complete'] and profile['passed'] and len(profile['records'])==2 and all(x['source_preserved'] for x in profile['records'])
 for n,h in cross['source_sha256'].items():assert sha(tr+n)==h
 for n,h in cross['model_sha256'].items():assert sha(res+n+'/best_learned.npz')==h
 for n,h in cross['prior_report_sha256'].items():assert sha(res+n+'/report.json')==h
 expected={'v23':7,'v24':18,'v23_position_v24_rotation':7,'v24_position_v23_rotation':17};assert {k:v['failed_cohorts'] for k,v in cross['summary'].items()}==expected
 assert all(not gate['passed'] for row in cross['summary'].values() for gate in row['gates'].values())
 plan=read(tr+'temporal_expansion_plan_v19.json');assert all(not (ROOT/tr/'cache'/(c+'.bvh')).exists() for c in plan['planned_splits']['confirmation'])
 meta=read(base+'package-test-v0.17.4.json');current={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT)) for p in (ROOT/'b4artists_ml').glob('*.py')};assert current==meta['runtime_sha256']==profile['runtime_sha256'];assert sha('releases/b4artists_ml_v0.17.4.zip')==meta['sha256']
 with zipfile.ZipFile(ROOT/'releases/b4artists_ml_v0.17.4.zip') as z:assert all(z.read(n)==(ROOT/n).read_bytes() for n in z.namelist())
 changed=[p for p,h in e['artifacts'].items() if sha(p)!=h];assert set(changed)=={base+n+'.md' for n in ['PROJECT','ROADMAP','REQUIREMENTS']},changed;versions={}
 for p in changed:
  snapshot=res+'diagnostic-document-baseline-v25/'+Path(p).name;assert sha(snapshot)==e['artifacts'][p];versions[p]=dict(path=snapshot,sha256=sha(snapshot))
 names=['crossed_components_plan_v25.json','ablate_crossed_components_v25.py','current_tick_profile_plan_v25.json','profile_current_ticks_v25.py','checkpoint_diagnosis_goal_v25.py'];inputs=[tr+n for n in names]+[base+'COMPONENT-DIAGNOSIS-v25.md'];added=[p for p in inputs if p not in s['contract']['inputs']];s['contract']['inputs']+=added;s['contract_hash']=g.digest(s['contract'])
 s['explicit_revisions'].append(dict(reason='Add frozen2x2 component diagnosis and current0.17.4 cost-center profiling. No model/runtime/package changes; original full endpoint, floors/milestones,50total evaluations and fixed15-hour resumed deadline unchanged.',prior_state=prior,prior_sha256=sha(prior),prior_contract_hash=old['contract_hash'],new_contract_hash=s['contract_hash'],added_inputs=added,recorded_at=time.time()))
 fp=g.fingerprint(ROOT,s['contract']['inputs']);paths=set(e['artifacts'])|set(inputs)|{prior,prev_ev,gp+'crossed-components-routing-v25.json',gp+'current-tick-routing-v25.json',res+'crossed-components-v25.json',res+'current-tick-profile-v25.json',res+'current-tick-profile-v25-process.json',tr+'cache/current-tick-profile-v25.log'}
 paths.update(p.relative_to(ROOT).as_posix() for p in (ROOT/res/'diagnostic-document-baseline-v25').glob('*'))
 e.update(contract_hash=s['contract_hash'],input_fingerprint=fp,artifacts={p:sha(p) for p in sorted(paths)},previous_evidence_recheck=dict(path=prev_ev,sha256=sha(prev_ev),changed_artifacts=changed,preserved_prior_versions=versions,all_other_prior_artifacts_unchanged=True),component_diagnosis=cross,current_tick_profile=profile,current_tick_process=process,preserved_milestones=old['passed_progress_milestones'],new_passing_milestones=[])
 e['regression'].update(rerun_this_iteration=False,retained_from=prev_ev,note='Runtime/package0.17.4 unchanged; retained330-case/31-suite and four offline checks, not rerun. Controlled component checks and two profiled source-recovery fixtures are fresh diagnostic evidence.')
 e['qualification'].update(full_goal_complete=False,temporal_model_qualification=False,temporal_animator_integration=False,host_shutdown=False,independent_usability='unknown',full_physics_acceptance=False,full_responsiveness=False)
 e['limitations']=['All four component combinations fail original worst-cohort gates. Fixed crossed tests locate contribution but do not qualify a model or generalize causation to other architectures.','Largest v24 positional failure exists before projection and persists under either rotation donor. Rotation changes still create some new cohort failures.','Current instrumented profile identifies private-copy pruning and ready-stage overhead, not uninstrumented/UI latency or human acceptance.','Known host shutdown crash remains. Runtime/package unchanged, prior regressions retained; no new full test run claimed.','Six fresh confirmation clips remain absent; all original full learned workflow, physics/refinement, rig/quadruped, connector, distribution, responsiveness, supported-host, independent animator and equivalent Cascadeur requirements remain.']
 args=['git','-c','safe.directory=X:/Scripting Attempts/B4Artists_Tools/B4Artists_Anim_Tools_github'];assert subprocess.check_output(args+['log','-1','--format=%H %an <%ae> %cn <%ce>'],cwd=ROOT,text=True).strip()==cp['publication']['head'];assert not subprocess.check_output(args+['diff','--name-only'],cwd=ROOT,text=True).strip();assert not subprocess.check_output(args+['diff','--cached','--name-only'],cwd=ROOT,text=True).strip()
 ep=gp+'component-diagnosis-evidence-v25.json';write(ep,e);obs=read(gp+'joint-mixture-observations-v24.json')
 for group in obs.values():
  for proof in group.values():proof.update(artifact=ep,sha256=sha(ep),input_fingerprint=fp)
 write(gp+'component-diagnosis-observations-v25.json',obs);end=time.perf_counter();duration=end-cp['next_controller_monotonic_start'];event='controller-component-diagnosis-v25';assert event not in s['work_events'];g.record_work(s,event,duration);result=evaluate(s,obs,ROOT)
 assert result['round']==40 and result['decision']=='iterate';assert not result['implementation_progress']['new'] and not result['implementation_progress']['lost'];assert all(not c['regression'] for c in result['categories'].values());assert s['history'][:-1]==old['history'];assert cp['max_goalposts']==50 and cp['resumed_run_time_cap_hours']==15 and cp['deadline_unix']==1788902277.2365775
 write(dest,s);(ROOT/dest).with_suffix('.md').write_text(g.markdown(result),encoding='utf-8')
 cp.update(state_path=dest,contract_hash=s['contract_hash'],input_fingerprint=fp,round=40,remaining_evaluations=10,decision=result['decision'],stagnant_rounds=s['stagnant_rounds'],evidence=ep,active_jobs=[],next_controller_monotonic_start=end,current_turn_classification='Progress: controlled crossed tests isolate v24 position-selection regression before projection; fresh current-runtime profiling identifies private-copy pruning as a bounded latency target. All candidates remain unqualified and original full goal incomplete.',work_accounting='Recorded controller-component-diagnosis-v25 once from330118.2559771; diagnostic49548 and profiling49454 terminal.',next_safe_actions=['Read original objective/checkpoint; preserve50total evaluations and fixed15-hour deadline21:17:57UTC.','Route and test bounded private-copy bone-pruning batches. Restore original context and Object mode before each yield; compare exact poses/metrics/source recovery against0.17.4 and protect cancellation/invalidation. Do not promote if performance/correctness gates fail.','Keep frozen learned candidates and confirmation sealed. Position-selection training, not projection alone, needs further diagnosis; do not retune exposed development cases.','Continue full original learned workflow, physics/refinement, rig/quadruped, connector, distribution and responsiveness requirements. Independent animator assessment remains pending; do not repeat or fabricate.'],recorded_at=time.time())
 write(base+'checkpoint-component-diagnosis-v25.json',cp);print(dict(round=40,remaining=10,decision=result['decision'],stagnant_rounds=s['stagnant_rounds'],work_seconds=duration,full_goal_complete=False,next_controller_monotonic_start=end))
if __name__=='__main__':main()
