"""Finalize broader reference evidence only after native and reload checks finish."""
from pathlib import Path
import json,hashlib,ast,difflib,time
ROOT=Path(__file__).resolve().parents[2]
def read(n):return json.loads((ROOT/n).read_text(encoding='utf-8-sig'))
def sha(n):return hashlib.sha256((ROOT/n).read_bytes()).hexdigest()
def write(n,d):
 p=ROOT/n;assert not p.exists(),n;p.write_text(json.dumps(d,indent=2,allow_nan=False)+'\n',encoding='utf-8')
def main():
 tr='training/b4artists_ml/';res=tr+'results/';doc='docs/b4artists_ml/';runtime={p.relative_to(ROOT).as_posix():sha(p.relative_to(ROOT)) for p in (ROOT/'b4artists_ml').glob('*.py')};assert runtime==read(doc+'package-test-v0.18.0.json')['runtime_sha256'];rows=[]
 for profile in ('boneforge','rigify_basic','rigify_default'):
  old=read(res+'broader-shape-workflow-v1/'+profile+'/report.json');new=read(res+'broader-shape-workflow-v2/'+profile+'/report.json');reload=read(res+'broader-shape-reload-v1/'+profile+'.json');assert old['complete'] and new['complete'] and reload['complete'] and old['runtime_sha256']==new['runtime_sha256']==reload['runtime_sha256']==runtime
  for case,prior,fresh in zip(new['cases'],old['cases'],reload['cases']):
   assert case['case']==prior['case']==fresh['case'] and case['source_restored'] and case['anchor_payloads_unchanged'];baseline,shaped=case['variants'];old_shape=prior['variants'][1]
   assert baseline['contact_gate_passed'] and baseline['priority_gate_passed'];assert shaped['contact_gate_passed'] and shaped['priority_gate_passed'];assert shaped['max_contact_drift']<=2e-4 and shaped['max_contact_rotation']<=.001 and shaped['max_priority_matrix_error']<=2e-4
   assert fresh['discard_passed'] and fresh['keep_restore_passed'] and fresh['source_scene_unchanged'] and fresh['exact_saved_contact_metrics'];assert sha(shaped['scene'])==shaped['scene_sha256']==fresh['scene_sha256']
   assert old_shape['contact_gate_passed']==(case['case']=='reach_hold');assert len(shaped['contact_solve']['adaptive_refinements'])==(0 if case['case']=='reach_hold' else 1)
   a=[r for r in baseline['derivatives'] if r['epsilon']==.015625];b=[r for r in shaped['derivatives'] if r['epsilon']==.015625];derivatives=[dict(frame=x['frame'],baseline=x['max_angular_jump_rad_s'],smoothed=y['max_angular_jump_rad_s'],relative_reduction=1-y['max_angular_jump_rad_s']/x['max_angular_jump_rad_s']) for x,y in zip(a,b)];assert all(r['relative_reduction']>0 for r in derivatives)
   rows.append(dict(profile=profile,case=case['case'],old_post_smoothing_contact_passed=old_shape['contact_gate_passed'],old_contact_drift=old_shape['max_contact_drift'],old_contact_rotation=old_shape['max_contact_rotation'],contact_drift=shaped['max_contact_drift'],contact_rotation=shaped['max_contact_rotation'],contact_checks=shaped['contact_checks'],priority_matrix_error=shaped['max_priority_matrix_error'],adaptive_refinements=len(shaped['contact_solve']['adaptive_refinements']),derivatives=derivatives,scene=shaped['scene'],scene_sha256=shaped['scene_sha256'],reload_passed=True))
 crouch=[]
 for profile in ('boneforge','rigify_basic','rigify_default'):
  d=read(res+'shape-aware-crouch-v1/'+profile+'/report.json');assert d['complete'] and d['source_preserved'] and d['runtime_sha256']==runtime;row=d['rows'][0];assert row['complete'] and row['contact_gate_passed'] and row['priority_gate_passed'];assert sha(row['scene'])==row['scene_sha256'];crouch.append(dict(profile=profile,contact_drift=row['max_contact_drift'],contact_rotation=row['max_contact_rotation'],priority_error=row['max_priority_matrix_error'],scene=row['scene'],scene_sha256=row['scene_sha256']))
 test=read(res+'shape-aware-contacts-v1-test_b4artists_ml_shape_aware_contacts_v1.json');assert test['tests']==4 and test['assertions_passed'] and not test['errors'] and not test['failures'] and not test['skipped'] and test['runtime_sha256']==runtime
 original=(ROOT/'b4artists_ml/contacts.py').read_text(encoding='utf-8-sig');research=(ROOT/tr/'shape_aware_contacts_v1.py').read_text(encoding='utf-8-sig')
 def func(s):return ast.get_source_segment(s,next(n for n in ast.parse(s).body if isinstance(n,ast.FunctionDef) and n.name=='correction_steps'))
 diff='\n'.join(difflib.unified_diff(func(original).splitlines(),func(research).splitlines(),fromfile='runtime',tofile='research',lineterm=''))
 audit=dict(runtime_source_sha256=sha('b4artists_ml/contacts.py'),research_source_sha256=sha(tr+'shape_aware_contacts_v1.py'),function_diff=diff,original_position_tolerance=2e-4,original_orientation_tolerance=.001,original_max_refinements=4,thresholds_unchanged=True,runtime_unchanged=True,reviewer='author source audit; not independent')
 write(res+'broader-shape-source-audit-v1.json',audit)
 write(doc+'goalposts/broader-shape-review-v1.json',dict(independent_review='unavailable',reviewer_attempt='adaptive-code-review.py --help',exit_code=1,error='uv trampoline failed to spawn Python child process: entity not found (os error 2)',author_source_audit=res+'broader-shape-source-audit-v1.json',independent_assessment_claimed=False,recorded_at=time.time()))
 summary=dict(complete=True,rows=rows,crouch_regression=crouch,native_lifecycle_cases=4,fresh_reload_cases=6,contact_checks=sum(r['contact_checks'] for r in rows),runtime_unchanged=True,runtime_sha256=runtime,production_promoted=False,full_goal_complete=False,independent_animator_rating='unrated',limitations=['Controlled skeleton references; no bound production meshes.','Mechanical root-yaw motion is not a natural turning gait.','Local priority derivative probes do not qualify whole-motion plausibility or style.','No learned temporal qualification, native viewport testing or Cascadeur comparison.','Some host runs overlap; elapsed measurements are not controlled performance comparisons.','Native assertions precede the known host shutdown access violation.'])
 write(res+'broader-shape-comparison-v1.json',summary)
 lines=['# Broader authored-motion continuity research','','The 0.18.0 runtime and archive remain unchanged. Six new actual-rig references cover a reach/hold/return and a mechanical root-yaw transition on BoneForge, basic Rigify, and default Rigify. These are procedural skeleton fixtures, not learned motion or bound production characters.','','## Contact-aware smoothing result','','The previous body-smoothing -> contact correction -> final smoothing order passes the hand-hold cases but violates the 0.001-radian contact-orientation limit on all three turn cases; BoneForge also exceeds the 0.0002 limb-unit position limit. Failed results remain in `broader-shape-workflow-v1`.','','The new research solver smooths its private corrected action before validation and checks quarter intervals. Its existing adaptive refinement then sees cubic-curve errors. Each turn passes after one refinement, with the original position/orientation limits and maximum four refinements unchanged. No failed candidate is published.','','| Rig | Reference | Contact drift (limb units) | Contact rotation (rad) | Priority matrix error |','|---|---|---:|---:|---:|']
 for r in rows:lines.append(f"| {r['profile']} | {r['case']} | {r['contact_drift']:.9g} | {r['contact_rotation']:.9g} | {r['priority_matrix_error']:.9g} |")
 lines+=['',f"All six scenes pass {summary['contact_checks']:,} independent contact checks at 1,281 sample times per scene. A fresh process reproduces saved contact maxima exactly and checks authored priority matrices against a newly generated authored-pose preview. Keep/Restore and Discard preserve the original source and rig modes.",'','The revised contact solver also passes the original crouch/recover references on all three rigs, preserving contacts, priority poses and source animation. These three regression scenes are separate from the six new references.','','## Local transition measurements','','At the same 0.015625-frame derivative probe, maximum semantic-joint angular-velocity jumps change as follows. These local measurements do not establish full-sequence continuity, physical plausibility, or animator preference.','','| Rig | Reference / authored frame | Baseline (rad/s) | Smoothed (rad/s) | Reduction |','|---|---|---:|---:|---:|']
 for r in rows:
  for v in r['derivatives']:lines.append(f"| {r['profile']} | {r['case']} / {v['frame']:g} | {v['baseline']:.6g} | {v['smoothed']:.6g} | {v['relative_reduction']:.2%} |")
 lines+=['','Four native lifecycle tests pass: failure during smoothing removes the unpublished copy; cancellation during cubic validation restores the input; a changed contact rejects without undoing the user edit; and successful correction preserves editable input and source recovery.','','## Remaining work','','Integrate the accepted ordering into an opt-in runtime path with explicit cancellation/rollback, contact metadata and UI behavior, then run regression and package checks. Preserve axis-angle/quaternion-sign rejection and adjacent-curve preservation. Wider animation, proportions, bound meshes, viewport usability, animator assessment and learned motion remain open. The full original goal is incomplete.','','Independent review remains unavailable because its entry point fails before starting Python. Author inspection and native checks are recorded separately. The native host still reports its previously isolated shutdown access violation after completing assertions; clean process termination is not claimed.','']
 path=ROOT/doc/'BROADER-SHAPE-RESEARCH-v1.md';assert not path.exists();path.write_text('\n'.join(lines),encoding='utf-8');print(dict(cases=len(rows),contact_checks=summary['contact_checks'],native_lifecycle_cases=4,fresh_reload_cases=6,runtime_unchanged=True))
if __name__=='__main__':main()
